apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./cilium/ks.yaml
  - ./longhorn/ks.yaml
  - ./openebs-lvmlocalpv/ks.yaml
  - ./cloudnative-pg/ks.yaml
  - ./metrics-server/ks.yaml
  - ./gateway-api-crds/ks.yaml
  - ./gateway/ks.yaml
  - ./flux-webhook/ks.yaml
  - ./flux-operator-mcp/ks.yaml
