apiVersion: v1
kind: Secret
metadata:
    name: redis-credentials
    namespace: database
stringData:
    password: ENC[AES256_GCM,data:uePdZeeHC47ZFahu87CS4RtAuKnw4lGz9pRAi7sD4jxJV16A8J1uRc+vrQOrY/LK,iv:EqirToMhuiZTLgrEzg5Lcy46XF6FYO29fxj6fv3toFA=,tag:eUOqCm5GQczLkbvYIs2XRg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhMzJvVW1yTkFqbWxJTHBR
            T3dSMG13Q2s0SmdFVVA1c0x3bHBOVmJlNEVFClVvZ3BhanNEWFloNDFGSFJCeXY5
            WWdmYnFUVEZDZSs5Z3o5Y3E2cjFuWGMKLS0tIHpRTkhVd0FSQ1A4eS9jWW1qSkJ3
            VU95MWtGUzBGRElDRHBpSHlKcjIxQUEKIuosSZ9tT99O9/R8+f76Kzm2mHY5BLM9
            MpzfjwhkADhZOGaicMRVpxsUpPX4Igj1rrwY9Osh1fXH8Nu2n0kYpg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age135zaeaxu0elyxn9ax64dgw9hsxk2frpnqpj672w23qgcc8ewza0srpk0pc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T20:06:26Z"
    mac: ENC[AES256_GCM,data:aWXLdvXtQR+mqjAccsesb3G0SyL3xo7Tvs4LFdh0JCEJpolxIbUstXtCCLe7XWYjBdzwjrPgiReCX68ZT8+q2wnoLgeaJDjQk3hDuDrmsgekIRB9qkP7QW5HYQGKKlIm4EGmSaw0kJUcmIJLzg2QTLT8kY4ya+BRcjDjE4N+18s=,iv:5stiM6VD5IpWxmklKSoXyShhF1p1KvUI8cj5qVo64mM=,tag:SIaDEzsXp913dL6Xi4yYwQ==,type:str]
    version: 3.13.3
