# AirVPN credentials are encrypted here because the VPN sidecar loads them as environment variables.
apiVersion: v1
kind: Secret
metadata:
    name: qbittorrent-airvpn
    namespace: default
type: Opaque
stringData:
    WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:Dy2oV+9gYip7pEE/MWj5V/Fyfl2BUQXzvPlUkse1KwICqba2rNPcCEVn878=,iv:lgUwGsNLaCW+WsEzjmlvJua5jJjnmTXvlLwUBVl0r2Y=,tag:6BfWYUuvUCNpa6AkpSuMBg==,type:str]
    WIREGUARD_PRESHARED_KEY: ENC[AES256_GCM,data:M0qmGCjnZHrL+hcCTQdYujJwrafgidXKp/7U8YBn2OPv5vT2iWUk3/u72dk=,iv:YjPmV3Rx+tDiAiOFvdoIWFmlXLKC0QN09XY4sPr5idY=,tag:ZB9G4bm3V5DccHo7Gg4wSQ==,type:str]
    WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:2+OGiPM5gHOoqH7FYZg3MA==,iv:48xWJC7Gw6s9IVUAxV1B0GRv18rKubj06AyrUlKzhI4=,tag:B0IoWibPfkU78sNxfWLEbA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQV1VaQVFNOGIzRjBWMy9m
            MzFUU0RSNUJZaUVyWU9aWHowRXg5ZDl6Y21FCjA3UGlzTGR0c2Vvb0JBM2dFbmIw
            dWJFUXpDVmtTNDkzWmlPWllRL0RPSGcKLS0tIFY2bE81VlZmWVFoNmVGTi85QkRZ
            OUtSVndmeVlFY3BwdjhUZERVSWVFZjgKnOChZJHaJn3wUFwdlUF9lQmMN2XCgwvt
            DDqtNshwLlxhhkK5xOH07Mg2PLWPmfYypKzHy09K3wsWAVkvqxw0RQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age135zaeaxu0elyxn9ax64dgw9hsxk2frpnqpj672w23qgcc8ewza0srpk0pc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-02T22:20:57Z"
    mac: ENC[AES256_GCM,data:5KhbRUPIQQV60xag1IYHLyZK8GQ5InOVQtbn0jHfH8da27hufgynasqbofwVW5x5lfNoK9AUDFp/3JD+mGFNLiwE/dVwF/olRyBEB0R4moUnq93BSYe4Nvbt2qap7zjcMJqBy2MOCCqWSyZJ/YhZOMxuHfHHZccE7E0AHIlbI4I=,iv:mC9MhN1/U1sl7QUzzkHy0HYzSsrJ85sX7e/wGgEPF0E=,tag:a/PBOYG4A5MqPtLRTRIU5w==,type:str]
    version: 3.13.3
