# SABnzbd reads TorBox NNTP credentials from this Secret at startup.
apiVersion: v1
kind: Secret
metadata:
    name: sabnzbd-nntp
    namespace: default
stringData:
    username: ENC[AES256_GCM,data:BjoiAQa0OyRjuJUGpYrB1gxBvBWS/Mf9JVf11fg7XRmgIHMA,iv:wzrt3w9AAkq8DhBGXTE2cyW6TijvhzIAJRsVNw04+Q4=,tag:oB2bFARBmUBXmQC/I0OFOw==,type:str]
    password: ENC[AES256_GCM,data:S1lmltZvo/CJ9C6WNL78DpqNzvx/0A==,iv:2Ebfkoex2Pn0PBwY9SlZvbDvebt5jj/D2Ru3WRqHQFc=,tag:xlwiT9+xFP+pqK8m/ynnRw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzWlVuaDIrM2JxOHVrVmVE
            Ull3UnRGSEkzRUh4cGRXZmRpVDNxRzN6aEU0Cjk1TitJeExENVBHZ0N3YlZNVGx3
            SWU2RmdoT2pVUk1HdWx0Yyt6TjdqQkkKLS0tIEp4Wmxmc3F6MU9aUjJlRm5uZlY1
            bTRZOUx4cHAwaUNmRnZGSFcrQ0h2V0UKWNmWXBT0iWVvZbVoI1APFEVnvzvmWBbh
            fRYTbxQUyLmQr1405VXwfbb3xVXTqHM2oJby9yIcSxE15ibQIMzR6Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age135zaeaxu0elyxn9ax64dgw9hsxk2frpnqpj672w23qgcc8ewza0srpk0pc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-02T21:46:19Z"
    mac: ENC[AES256_GCM,data:ggqfTMt2L3KsyQVjaU1LTRNYOYWDNwBBgD1E12J0zgbiwBgFQo3dq52VKHwFYAlaHyB5SdPVWVjCPhKk8fd4yODoCxw+BSsmUrLKDImxIFd8TEJAeEbfF4EFITp+s8JzyJ/vlgm2UOxkZ9EFUuzSym1WwuQTYISyxRLH4dxyO3A=,iv:05kC1SVJSiT9rudGn82coWjW54J9+iEZfLmvNZH+Gdo=,tag:tiImRmKThM4EKs3Pr2RH8g==,type:str]
    version: 3.13.3
