# DrunkenSlug API key is stored separately so the indexer can be restored without exposing it in Git.
apiVersion: v1
kind: Secret
metadata:
    name: prowlarr-drunken-slug
    namespace: default
type: Opaque
stringData:
    apiKey: ENC[AES256_GCM,data:tcmrK5FXQGY5d/SNaVDZ27jXZUmzG53lLe43Rkk5Mdw=,iv:pnWi0Bxj0wkKbRCK/tbIdX+eO8VXBaV+1b8GbCdrPYU=,tag:7qCwPsaCiJlowtAIxXoXQQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwbHN1bVdndmEwYjZaQWxt
            MTVLRm9KKzQ5RHdVQnhtT2VhbVMwU2laN0RFCk1xUDZyTXByaFdsaHUwNy9IUkRE
            bzRjZG43VGlUNHFmbmYweVlndk96UVkKLS0tIGRBaWR2U2N1ZEFuTjl1MzlSNWdM
            c2l1eEVsMC93NHArdGZCTUJPM3A1K2cKJQEhvNMTt5OB+AM92UoV+2zpp/weAsRI
            yRpcuTt3CDA76UyybichZHmS3UgT44Qfm1A+qmLGPkjoKmCJpAXNKw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age135zaeaxu0elyxn9ax64dgw9hsxk2frpnqpj672w23qgcc8ewza0srpk0pc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-02T22:22:42Z"
    mac: ENC[AES256_GCM,data:PqxzSrhpi2QZv1LDjTbAIe6+9bWSpdH3VNKStQOIXqbKAw+lp/Jxwg+e2OQ0yQcKGApeVm0A7gSNd2HWXgn7bdT3lnhmezTv5PMVRt1CpZn1njYO76xH6Y38QJ5yzjPtVXMGU0To6DYfNP9IBUFXg4nYNtYV1ViSGOsJpaYV2vU=,iv:kck6veFhp9phpB4do8bUido58jf3DKw7lEm+d4xubCQ=,tag:lqRGHaUKjKLGeLmCsSzeww==,type:str]
    version: 3.13.3
