# Same password as grafana-postgres-credentials in the database namespace -
# duplicated here because Grafana's own envValueFrom (a Pod env var) can
# only reference a Secret in its own namespace.
apiVersion: v1
data:
    password: ENC[AES256_GCM,data:Djr2vKFSotATJXzo/qqyIrYvyDJlQq0QPWbPYDrb40pGjIDM8oYMeQF3JE0=,iv:7huz5L2JVkt8HKAqOYSuj9+FoDKQ+cfYHtYGHbyjaP0=,tag:vq49oTesajafZxm5bmo9IQ==,type:str]
kind: Secret
metadata:
    name: grafana-postgres-credentials
    namespace: observability
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3SUgrREJKWEJ4eVNQVjhW
            aW96dDlZczB1MmtUK0xZUWdwc0hJdXhjVVZ3Cmh6UmxFWGtDWHBYamlmY1dtTTdr
            RG1uelN4c2Z5T3JqY0lQcmpINDFwNHcKLS0tIG82MnBkdFBsR2xabEpkbmdRZ3Bq
            TGQyUmh0d05XbFZ0SnhheGNzd2ZFZ1UKy0RNPL4p+4myO8lXhN/O0AGUpFiwtlUw
            LpaSobfcuUKjHypPC7xbebxgVtNYJej3MWz3jMn+sW5Sm1oU9bGO9Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age135zaeaxu0elyxn9ax64dgw9hsxk2frpnqpj672w23qgcc8ewza0srpk0pc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T22:22:25Z"
    mac: ENC[AES256_GCM,data:Gi7tyR+zC97LL4+a48399ysJ7C5ZRdenICGIho9P4oPy9vVHmBzyTX/GxQNyCf9uZ10zX55ruISzPrq5NICEECxCcvOt/iTu5rGQbOBj/AkiEr79UhNqQoJp1ltcUG6z7Fvexl7gNoF460cnSiwjyPxmSxghXhEowYPzbtHC5Nk=,iv:ygW+Q3XaQNOZgqAzFbaPhjHeLft+SKLrtvhp6f9MC3s=,tag:xVjfIklVUC/bCNwClD48mA==,type:str]
    version: 3.13.3
