apiVersion: v1
data:
    admin-password: ENC[AES256_GCM,data:Rnrfjv3vFxb9qAMN6OhkjigeWqNYDy7OdGcueFopehdIUM1xOUlUbcOzpGI=,iv:2hSlWHz+YO9PXE6FN7e35oT4YbogoHhfTh9VTRJEV38=,tag:hPraW9TbqrDOCMfZdj/xRw==,type:str]
    admin-user: ENC[AES256_GCM,data:qSW/xZgIQk4=,iv:tJ6vNIpYGARLJdFevapmce6S3pRZ4tD83gp1xT4drFc=,tag:V2reZcw00i6LsyTsTpz7EA==,type:str]
kind: Secret
metadata:
    name: grafana-secrets
    namespace: observability
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLeCt5S0Z5N1V6dk82NGNn
            bXBTQmF2cnlIT01KdzFjbnFnOTNtdG9vY0NRCktYWFo1bWtUckRCZTF2c1dtZVgw
            ZFF4QllOZFd6QThNMUxMejM0dkEveWMKLS0tIEk4OUpVN0NZbGJsNE11Q1dtTFVZ
            ZzA5ZGhvbmhlUWpOamxncFpQUC9kNGcKClEu+9EPy4iwb7I4oYa4xvdvxvV+Zb4A
            6G12Yhi0Qr6YIJVzUQDSTTeJQMxdkNsZVpMAmXnRyTU2Ljd15r/j5w==
            -----END AGE ENCRYPTED FILE-----
          recipient: age135zaeaxu0elyxn9ax64dgw9hsxk2frpnqpj672w23qgcc8ewza0srpk0pc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T21:53:20Z"
    mac: ENC[AES256_GCM,data:DXrx7+ajuXcN36CnVfD/QA4GlsUXeOLn/WnK9b+GPCe2ozHnnBUI8iu4hVuTv2pXv1zLMQ00oouZUq3Oo6cNKSq+wC/BcATSo5j0ZZOPv6PafgVJlxmrQ1RgBf8ngWZxvtJPswZi0KdvmgRpIPvIn8MsyUsXKdvtKajt0A1VC18=,iv:vakW0IiX6nnoFDHm8T3PgqWU37VQSSnTk+787/xzaFM=,tag:wvSbiJ8uuJjuDjbC1HsrRw==,type:str]
    version: 3.13.3
