apiVersion: postgresql.cnpg.io/v1
kind: DatabaseRole
metadata:
  name: grafana
  namespace: database
spec:
  cluster:
    name: postgres
  name: grafana
  login: true
  createdb: false
  databaseRoleReclaimPolicy: retain
  passwordSecret:
    name: grafana-postgres-credentials
