apiVersion: v1
data:
    .dockerconfigjson: ENC[AES256_GCM,data:qxvRXa12oysU1ULQbtJtdRxiAOf/LGe7H2RUwfJEzns06Grw4gQwP/uMQrsAFBVUh7IFyyRnWf/pkM9Z4WeWCEczzQnKffVqkS0RrCqpTJp4LYfD10TYa2Iax7zsVebRexuHYmACHWidLcJPcI6w8FVQJC1R7Qg9cGr9OxlPvKuK8HVorRI2L0ITZr6Swt5IS0soho+U6kGPpwHxRPqvn6DB5TI78aNkMErC95NUOnYKrqqvu9586aBC/VVi8J+llj3KWJnqOT4CwKt9S0AD6kB0z/n/4WpqdwmvEzydcLKkoKMzVEmCkL1gxzU=,iv:ZuEg11rHQX22KcZuSXXuphNasT4Wn7B8YfUwqglgE4I=,tag:Bn6nWJIfZr5/oR+VPn3XfA==,type:str]
kind: Secret
metadata:
    name: ghcr-pull-secret
    namespace: default
type: kubernetes.io/dockerconfigjson
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5bXJaUTdIUGIva3VJR0Fq
            a3dIU1prNEozakJHSEhGempPOHIrSHN4am1rCjVKYU1keHVQRDF3RTk4MFl1SFB2
            Um02NmYveHNIcVgrd1JwYXZpaW56UTgKLS0tIFZUeUJCdzRCL0c4ZGNnbEVlV2Va
            am5tRjlmZmFSSmkvM3ZDODROWER4U3cKYr7mD7h8ScaKhLyPqjCLN0vZT+aNrYWJ
            hzzvmlFbvYAmr4yvqD22xMyYos0wbINFhyr8loeRpZT6vM8ZZsiPJQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age135zaeaxu0elyxn9ax64dgw9hsxk2frpnqpj672w23qgcc8ewza0srpk0pc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-18T08:11:55Z"
    mac: ENC[AES256_GCM,data:brg+yUXz9StxR5CA1UqxURk87HQdb817JvPN6f565v4e6yYLdfgJX8h3G9vlAINZNx8uGDLiH3XlOiKFjzB6gdx0OtGbOTTY+roR4q4FHsjMC4UP5ds9fa5ksXoAoVAo+WbHdbnHC9Ph1pzIJvN/LY7UvEv8FxUZNCgHSVeheBA=,iv:RiNZJqlR2mZR7nn3VUFs82zxQHwPQOVDvnc12dhVdS4=,tag:xWj7ZHELQJToMTy743aihQ==,type:str]
    version: 3.13.3
