apiVersion: v1
data:
    config.yml: ENC[AES256_GCM,data:oWbZg6G0r5FWCk5hr/t9l7ZZSf36d4qwJm7yMeh9jgO0iYme5MqGFkGUCoeip6VNaoJpUScgjUU1flOHN+t6v562Sz/F3cpnC+8ZKshULTymqL4qEXR6PO3PQa5xDYs00uFWsBcgoZB5d6aTmVO/vdAHlnkBN9KOuhgvwdemd+XRfhzPabHgho9U+wLIJY9AQ/fFXCkPhsanJC0FYxQKRFbOymPGX6kasyKznSNByDWfjqh3EJnAkwi86bo3cjOfWyXzuY7BzG1Lz1AcwEomLBAORgTu7c+43IPPqkVxwT+tDuWFBQ3QHNhsQ8wUsCiEXggVdkiBzNZrOzxMTIc2J7q84wr+ZX7WzPbW32WNExYe8/q9dGBATb7McFssk9vAuTT96mPHdL2wAjdHKeEinJRAdHDn0HnKmzC+cBOUDCEhtF8pNYT/zlnUne2KbVIL5xSG6hNc1z11HF5i8lik5Ba6f4cLEz0slhvW2JBzI2kbN5Appyxgi5bpwfszbSPyH0IgzDp/Cb47IlkvR5yBpUy0bWwDr0mpb2WVcvrC8x7dUz0Ik2rGRnmGoRfcAUvJYL35q5F88vk/jsJya087kr3ZAArAkb09Ow2QBtpOed1oUbSVsYRxZFy4Iuy/2q73wKgxM1khX3MMgaQV7/7Xvsg85yLUqEfnMwgUI+Moj6sf3Txc3gn3nRx+fRNITDCWgmubNkcPTKMcoHhniGHCX02X6lj+OD4cMJzH7mELRw8uMzFfhBGG19jZ19aHEe3OkMDp5ktrLjxflbthoV1EhfEFCyTyl3m1hSNPMZN3iejwOzmn2Tvu1i8bztbDEzWJnoJ3S+9N11Nn9/nHmEO4xShY0+jS5omxxqrc1qI6BWedReMtWNX94BIVmkb1BzqV6J7vmHhTMO9QDgIkpxvMB+f/KilWaVfv2rrqOOoH8r2v1oV/gStR0u1BHynjRQSXu9JZsEdCsjQPBBeoOvGA5yDd6r5uQx5pQ2FjInDe/QwG8iy/byavEt7senKNt7rnw2/y6p1tLALyzqqpPExdBtj7gSaO/V9UeTjawep1iI5X2IiEzribFuI1FwCZ0YX5WZjWrk2vKs7sE0vtPpaiIVUAzETZiF+8gBAQl4yDxA0gIQEPfpdpQkS+xWQMew+wFlbzApR7cE5XIBYXPSf524OMGCMQFbrGwnK2Wz8Y6DZqewObI0HN1sZEJx8IXH+IvoGg78wkvwk3KzhzeRwa2uFf5r09us3ABF6oKJSVOzN+zi/iujHLV3s3PEZ9jV3TBZ3WF1Vk0znAxxM6ERXRTBmdPzowG6ZxAhYcWy1Qh+tTgEoUsXTwFAzR7GD58RtWUWj5VrCI7sq4569qW+VeML4vwLmNoFrdOj4ZnHaBo1xYBr3xVQPyx7wYsprbR7llt69QoSSnP0XYS1+5IolHYWY5+wtaNCW0PFp7iIXKVWRRrz2DmuMFicV3PUvaFo0gunTRv13lDneKMQEDX2zKlbb/vRG/P0i3srryiKFjjv0YBOiWAaA2IbqP1F66ccFp1Xzu75e97RSGPfmb,iv:2Xe/jt222FZiSDkXWdsm66sXdiCaO/RxBPM2sZpQByg=,tag:G61jJ0wmI0Zf7tzzipsv+w==,type:str]
kind: Secret
metadata:
    name: zurg-config
    namespace: default
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5bnRxQXhUZ2NxRG9iSEpY
            bE5nMU5KVmZndTJmVzNZOG1rZ0c0TnRmU3hzCmxlek80S3JKMFJpS2d4SDJETld2
            dENMNnNKcjdSNDNkbWYrcTNrQzJOVEkKLS0tIFdVVHhtSnVEWStsTVNHckN2OXpl
            MGVDZlRtNnhSQXB6SG82U210azJPTDgKNvmzdmxSq9afybwStG7RhZ2OecALfZIC
            60UCYjHbL5vzVd6HrrD1gOs/MZmUmbsPENIPRxmfyqAi1C3b+iRWZg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age135zaeaxu0elyxn9ax64dgw9hsxk2frpnqpj672w23qgcc8ewza0srpk0pc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-18T08:20:10Z"
    mac: ENC[AES256_GCM,data:32BDMyPtdyewP+hv0/Wy9IT/CLbz/nvHuhrt4pkGh+REYWdbwxkDCggSdsgV0t9sO0SCX83EZlivExVhfsF5V9IUvoeYqdmn2saqyYuF3MHuvqw5RxGgf9xOzZPNJmNHGglSSE9UeMzPenP2Nculnk+CO+F2YXTHNEZXeSqvuHk=,iv:NbOhtFFuZJ9SRdwc+ALYBXkKYop6XqojmbSOLbGawco=,tag:BOX2H9Z3VuAtT/u+B/XSRw==,type:str]
    version: 3.13.3
