apiVersion: v1
data:
    config.yml: ENC[AES256_GCM,data:15TNhqLiD7PFq7zpkdvVz+cG4Bz9iApp1afUDPSoiDinulMzqTYTS1N5p9g37o4Cp1fhqAFCL4saOpGzzZtFiJT7XuwyKRy46x8J0pJfs4SEassLz9JhBjXw+U+xw39s50LJ40uV5j0KY8mWna1neE+7++e1bms896/uVSbkhkNUPqDeeU+Z0tWs/DRRmGk0PIvAaCPKNdJ+VDI5B9jxBa8WmG1wrSAgD2Oc1jXDVtS5a2xFd9HD7FosVaH7UE2PsfniUUIQKjXue9uPA06gqm3+hA9yrM8uRK7DpO99h/ie6FbJ7LhO7bS59/MA9catw4UGpH/l0FEyD1ncGXbyEXACjKboVwKGcpeIGBG1ypdjnAU6BBEOVKNhi0RumWasBSnh0R3zgD1qkc3x+DeLdTrGU3zy+Di+gQzQCcMtSMR2lJ6JVQ7rrZSjfcJQmKbpUZXKFLU2FZ8An2JjJODDAn8WrH2+K9z+rBU340dfROI+nr+W1XB8hNVicYx1ffA7j1gceNrqlp7pi+P9k/qb28PSQGQxdZLoUL5AzS8a7V+8lM6WoZPBNIY7KXhAna0Rh1fyU5PGUCfzxtRi+OCX8QaBCJ1Kz7mAnA9LgW8HKYetyLo7Yy0AW22m5Blz4IIotyo87FEVtAA1mqzNMA0Tv19KAdIvZ4hOk4PMpVgUmdSh+gvWiPBF/Of3xYse1GiG35xM0/pIMr4ouH5gtnBXQPsTlUez4fKnuldB6+gTVvmS30x/gnyIGaT2ARSNKcVQeZZP1qvDraW8p8XzStDg/aWlK1NYTtbfkazVMFLmF2T3qAVSjuM/c0FdR3EqGSKfNQLIXqvH0olsC5s4GhaJuLbi60jeRixUru+DMy3pq8G5bP8GifLnKVKNAOxbxKRKv+H34lniFto+BLIft7fadqTYiieMrGxCjEbnByb8DEF0l5GiMgp3V16HYjGIoWbr/D9Q0Veg5e6xbRHUW7jshLgcinAevk1EFn6KrZ5j5iIrj8wQnI8yv+F4ksdFt+G/odnkXe9RiQ3pGNIV0t8Caxi5grR1omysobXeJsbD/2VsRz6n+24ni8D2Ncrx8QscrMIH0WIPMrKQtM+fQz8ng2+Be3S4HaMcs1WCAeCiJ3CAkZejQ7jzhseTmbcCBu4aBMfhvdY6STYa1lpgKL4PR3904/9+U0Cx,iv:dsu2onKhiUX7Raav4kmEJCcJZUOoSJnMXb4TvNvG1gw=,tag:r/gD9UNvhFFDW5frBnL1WA==,type:str]
kind: Secret
metadata:
    name: zurg-config
    namespace: default
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHMkdHVmU3NnkyMWZOZGtn
            SWF4MnFtczFMZnM0NFV5ak0xaVJZbHpyNmxzCkp4WHk2eUFhazBMVjBFSGw0dzJs
            ZlhCL3RiVkhFS0wwS2tUcnpvTExxZVUKLS0tIG03UXNQTlVRN3VSbWhhUHBveVJ5
            czA2QnpoYXRodWZUdU01dmR5U0lBTk0K671TaZfhGnakI/i4xt8gCAHzULjULhL3
            SA0MmRJGpwv33ejS75hE1sZ7FALfGkWKmc/M/cVy6o+GEVcLihdaqg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age135zaeaxu0elyxn9ax64dgw9hsxk2frpnqpj672w23qgcc8ewza0srpk0pc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-18T07:44:07Z"
    mac: ENC[AES256_GCM,data:sEGFBEBwyAliO7gHogxvtKXiv2RV65tblQJug6iEjdwNm/51rfE6qQuVQrUk7eOPGgxapYFLBBOKRI9kIxF3etQtzjMcVIHW3m+sOUIzEmtW9w1NBXvMN5txPwSz4V85PArLF9fdCys48wFYZ3cl4JwPWE6OWdW+OeChx5Jzvds=,iv:P9RUyoBl0+uS5r84z7cNn/MkuvwucckjCso0xHij3ds=,tag:DTEfoeFDoqD4NsP9T1rI5Q==,type:str]
    version: 3.13.3
