apiVersion: v1
kind: Secret
metadata:
    name: proxmox-csi-plugin
    namespace: csi-proxmox
stringData:
    config.yaml: ENC[AES256_GCM,data:3ZDsepUsLfBqP4qVLPdHJLiih/KGG03RBJTO/sgHBusxU1oHPbWByvBEoYPN+1Uw11j/LYniNcz3+IBhsYJtk5cUkgJPaDFJ6OGtB9xEMkN5QxxPxPeKWxZX3zcvJnHofrSd9npDN5/1MRv1JaddzOZ/kVrpmXo/FKpdG/49lG7y7xb2sGXpnlZAXn6A0TcbIsrne3l4Q1+HA55r10p1Pt5/NYCuXuXcI4jpjdCN6mMC7QFHT3G10W8wlOaAZgo+qzUwR8/1JbkNKhDcqHjlD4eBeEtV5bl3jowWXUiY,iv:ksuInWOE+7iwNOWviOjhZFc2X10pVNCz1Cj7MFis3X8=,tag:2fZrjHKfBPGCZ57f2Rh8xQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNZWVmYTY5TmtBbERSaXNx
            NlFvU1pETjRWYkl5c2dHUWN5b2hTeTk3MW1nCkgwQjRIQm1EbEF6VFdVTGEvQlVN
            aTdVaXlwRGJNWmxtazB3QXNwYnVyQzAKLS0tIEx1MFBITUIwQlRtc0NTV1V3cTR0
            UHd2QUNubFFpRFQrODZvZDB5YnNUeHcKdRR7yFmP08fGdfh+Cq0r6ppZ8t0koh8s
            l0+018zPoAcOBO6oKM+69NWzv2HlbZaqE9IyoBaRaFVez0YGCus6IA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age135zaeaxu0elyxn9ax64dgw9hsxk2frpnqpj672w23qgcc8ewza0srpk0pc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T20:41:27Z"
    mac: ENC[AES256_GCM,data:7rZlzFe5cn6MEtyUCoDbu6wTQojS4Tut6aSD6P4/Xh3srAoNkv5oQB15V72tOR7GVGHzqCoe6FtYfbhbzN6CJCl5lnE60VP8auR9AhukTAPancg3byru8ZE9SWdMoVM6aB4AjuUeatZ3r+knuk2+b1DqgMOFlLhK8gpfG+FkfdU=,iv:rWAZvNCdXex4zjhPtp/EaN5Xa71gAz1V7+Yj3TUk75E=,tag:VRlmHzZEyyEdfLbsMhzYfw==,type:str]
    version: 3.13.3
