apiVersion: v1
kind: Secret
metadata:
    name: proxmox-csi-plugin
    namespace: csi-proxmox
stringData:
    config.yaml: ENC[AES256_GCM,data:saaZRQeWtBL93A2JZOjhnZE5Dcwlx3zw9WE26qAoCIJHcNyLnS/RxRoxZVEC8cxItWsAW+0IUWqXOWXBkpbQw0RQLmUOZwCeW2AMfk6sdQ4YxF6+7+G6k1oacWbQQgysKZradY0Yx4u0W682TmYbsEZD0F8FfM18nX43k/32hb+/2xX+RL2wWZMU+eEnzJm/Sam3bZwzmFmQGcaZgprz0VTdT8EcraB8Xk77E+FOr4uqCl2H2rfheSXxUZeGYILkXHZPdObO3g==,iv:BPJzNAP2LGCLAreQXzOOdfcRsFuMy41DWV41GPB86Tg=,tag:rlwbHl4P/ChjFPjqoh5hnA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1WmQ1OEdDMDMrNEdNK2w0
            ZHNncUpnSG12T2hpbW5MOGhzdHJlNmZvWXdRCmhRNW05VlBuS0Y3a2NIc0tpWnFS
            R3hZY0RLdm5vVGhSZmE1cVJUYzUxbUEKLS0tIEdFQklMTHpWamtLVDNoL1BoVUo0
            YVlmV3YzUk5jRHI1UVRySDE4QjgrdDAKhMJodwDMQjG51OgxtQ/A5QL0smANx379
            YxZ47k2hxLhWBN9FNsTOIcTYOOxLHQWYEST40EsFH7fDV4UWPXTIGw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age135zaeaxu0elyxn9ax64dgw9hsxk2frpnqpj672w23qgcc8ewza0srpk0pc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T20:49:18Z"
    mac: ENC[AES256_GCM,data:4Wfz4vfW0ld1mh/+dIpUdFVzRloO9p8y+MjlH18L9LONcSv5u7A9PrwWrC0JstqY6huYSZnI4w1DGoVOilMr/R3VaSzCzLqojNDLgQ3yZrARV1hi6wxDyoQhrGilfp+SSY5XEDUDLK9WxxUwhxycQAkkHFklG7sYTFN4fVBcfjw=,iv:gnykuO25NFUnsLeCi9491gBEdoUufCWpKSKtpHs+IhQ=,tag:DqQIyutHpJuD1lKOwT8dnQ==,type:str]
    version: 3.13.3
