apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cert-manager
stringData:
    token: ENC[AES256_GCM,data:9/7gzT1vsJU9lZo7ZIlrT+ltmDQVaVXKsYmmayPdtOlbhtDKfw/IAJdwYdXfh2kJUN55G/E=,iv:iMV9zrxuks74doIjTiuoMSfgjwMZk5hGdft7nTyQpOQ=,tag:mFVrCyGdhiSO3qRZh0daxg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNVE44dVl4MHZzcTNmVS9V
            TFR6TVhURmRGYnF3Z1VvVHFlZ1BmN285MGpJClVHQk9xdlBKWWVkNmdnMktsNFNt
            Z2pZL2d2ZFRnRnloRmhnUFhDcGpFZjAKLS0tIE1YblJXNDlteWVmYWJRSzAzOHY4
            ZmtVbHBoVmRuakhKbzhib25JOUVoR2sKA5lFez3+WYxAGBmHqr2R2A+QEvRmGecC
            aO3GOVaWYMNYCWQz3RFEuOLBkUl/XWc7f11N2R8sXcgPvtXXyrdaAw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age135zaeaxu0elyxn9ax64dgw9hsxk2frpnqpj672w23qgcc8ewza0srpk0pc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T13:10:41Z"
    mac: ENC[AES256_GCM,data:1LNtpNVY4SpZl86JRsSjooUWrZzP2419si4iXPNr4cbohIYqlkLp9ubnOaQbgeOa/xbDudngbQXjFt0jz8R8tE1PJlXmwX06N2vXT/Pa7VrGFL6vgy43J8XxCYqo6zw3iSI5OZ0slHPlU+lkQKJA1rh8dH1TkjjH/v+LdSRh+s0=,iv:dDZFd98pNJ8gdEtGeTIEfWlxdPac3J1y6Nh/r7Y/Smw=,tag:77XWioclRyjuQGIheJl8kQ==,type:str]
    version: 3.13.3
