apiVersion: v1
kind: Secret
metadata:
  name: registry-htpasswd
type: Opaque
stringData:
  htpasswd: ENC[AES256_GCM,data:bwWq70b21sRWhjo/NshCgmPTM6irT2Y9qE7wp+p34BtZFofcm5V1+MzFAkegQ1gws2IkbhD0Hgp5NrOvsw69mfRhqfJla1NeP7E=,iv:p2eBR1+SpmaB9s8981ZlUtY3D11gLX8Z6cbqadCHYDM=,tag:EI68t2OLmpEqtE4LvXrc/A==,type:str]
sops:
  age:
    - recipient: age1d4dxpuyj8g4y5nd6pruueqxnwsd050rnphk0xk3hmse67l3w75csgdx0ey
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYa3JENnViZUpseDdGbWpy
        TWVvazUwV3BVR0djbEh1U3IvYzlLU3dJSzNBCk9GWWlLOUQvL1hkZUdYQ2pTTmw4
        UkFIQ3pWeGt1MWoxSVVjcnc5UUluYTAKLS0tIENOZnppYXRYMTZlejVUL2FyU3FN
        dHpRQ1czMzNRTnU3d1hMMHBMNlV4eWcKdyvzjLkvJjC3IayZO4LV758RhPJR/iGt
        B9Oc8G3BCOrfcvmOOZgkKziIv1ijIlpQJkoURBCjKSHske+aNN7yCA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-08-06T20:33:19Z"
  mac: ENC[AES256_GCM,data:sTwi2yZdehSMX7EkaMCLGql/BM2FLZhV6h4W1fFOOsPvon8iWIL0kPf0I05//uOlXC4RDilS6mVJkXpEJ+amooFPRHDEEvEhiA+A83Ld+r88LM094ynLzhywEBw9YAdrwlt684XKfbNPNhjOobOuDeNYx6C5MlVFM+mYOp6440E=,iv:cKVOoiWebgufcSUiMOSwRaKTR3Wb4MbO2r2+Cs0yV7o=,tag:j3hDOHKX9zneaRD2abSv2Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
