# Same postgres password as authentik-postgres-credentials in the database
# namespace - duplicated here because Flux's HelmRelease valuesFrom can
# only reference secrets in its own namespace.
apiVersion: v1
kind: Secret
metadata:
    name: authentik-secrets
    namespace: authentik
stringData:
    secret_key: ENC[AES256_GCM,data:IUSm5YibQFy1TdeI7ntqlX19HRa5fY3s01mHgsYetI6Bg/siif5fg1cKoLdzPij/QifrlmvHMqa6L8k9Kp4d7A==,iv:c2M3AqSipfNryIKkiDnX/+UDGLzFhTBmA22Y2Phg3Bw=,tag:DqOnjr9Tt7B+7tuSp/3WUQ==,type:str]
    postgres_password: ENC[AES256_GCM,data:VVmNTTgoAadNblN3LE/uc6jJC2KIlaX7MwMSA+8HgoAafHU2UcvLzwj5VqkkVgMN,iv:DwVxH0wPZnC4DrxHq1QNNrFpOqSVwGZIGopYkCtNg8c=,tag:PBMUIGrrhgTh0YtUeJZhEg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBobGZPTnV0RVBJUlNrTFg2
            SXVuRlJmeWovcnRDTTFLTDVNOWhEYXpLd2dFCk1abEkvbENQN204YitUWis1bTkv
            RHNvZkZaZTI1Q0Rmc2U5WTVNcXNmYUEKLS0tIEVLeFVIOWVzNzhSREt5SnNFRXlW
            SXVlMFNoOXpkcGZTQ1ZZeGh4cDZvMm8KY/d9eBiI3sPumTmn9rxXamghBARvFlZ7
            l2CLLNFciceYjch0qQBOjNZcblDVlxjENtYH5qQOhYPgdY9xTlPfNw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age135zaeaxu0elyxn9ax64dgw9hsxk2frpnqpj672w23qgcc8ewza0srpk0pc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T20:08:13Z"
    mac: ENC[AES256_GCM,data:i1UPAhBEsmq6ByY0fiu8ytzVSRw66ASeDRWb3BY2v2ksuJGGds1itnZHV7CEnPmuZTBYiLoxrqsLXQzxamhp1AFYzcG7eNnbc0c7qbk/AxDEPYgj03zqfJq09f9UjVtQEH0C7xtQYJrKFPX7D0o9am7Dg/tBloM54zE63wnYgZQ=,iv:BuKx3HnUETseOBPr+MoJJ6UaELqFl1iZqvDIdTlBVnM=,tag:5INWsY2/VJRn1uthyDd6wg==,type:str]
    version: 3.13.3
