# Same postgres password as authentik-postgres-credentials in the database
# namespace - duplicated here because Flux's HelmRelease valuesFrom can
# only reference secrets in its own namespace.
apiVersion: v1
kind: Secret
metadata:
    name: authentik-secrets
    namespace: authentik
stringData:
    secret_key: ENC[AES256_GCM,data:IUSm5YibQFy1TdeI7ntqlX19HRa5fY3s01mHgsYetI6Bg/siif5fg1cKoLdzPij/QifrlmvHMqa6L8k9Kp4d7A==,iv:c2M3AqSipfNryIKkiDnX/+UDGLzFhTBmA22Y2Phg3Bw=,tag:DqOnjr9Tt7B+7tuSp/3WUQ==,type:str]
    postgres_password: ENC[AES256_GCM,data:VVmNTTgoAadNblN3LE/uc6jJC2KIlaX7MwMSA+8HgoAafHU2UcvLzwj5VqkkVgMN,iv:DwVxH0wPZnC4DrxHq1QNNrFpOqSVwGZIGopYkCtNg8c=,tag:PBMUIGrrhgTh0YtUeJZhEg==,type:str]
    bootstrap_password: ENC[AES256_GCM,data:P1OtUyJyvtq3sRmAksB3h6utGQu30yYplqmgLsv3hMY=,iv:00LMgU1GQeUGLQjrNBdfFeNrDmkfzB5tYLCraPn/zko=,tag:/RSyxhVDjmPgDWAH4fYNoA==,type:str]
    bootstrap_token: ENC[AES256_GCM,data:NI8fyml67MYEOAB3qFAAnVJEQGeChr/znAhhQxF224BmUJqM78NMtGcu6o76aiIJOUKk8snwN1gdeOlLiaTh/A==,iv:MhfoSreGJbyKu2Fn1yYisYRGI6b6sYngX9W9IMuKFYc=,tag:hvxMC2KQKOCbJmzW07xvlw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBobGZPTnV0RVBJUlNrTFg2
            SXVuRlJmeWovcnRDTTFLTDVNOWhEYXpLd2dFCk1abEkvbENQN204YitUWis1bTkv
            RHNvZkZaZTI1Q0Rmc2U5WTVNcXNmYUEKLS0tIEVLeFVIOWVzNzhSREt5SnNFRXlW
            SXVlMFNoOXpkcGZTQ1ZZeGh4cDZvMm8KY/d9eBiI3sPumTmn9rxXamghBARvFlZ7
            l2CLLNFciceYjch0qQBOjNZcblDVlxjENtYH5qQOhYPgdY9xTlPfNw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age135zaeaxu0elyxn9ax64dgw9hsxk2frpnqpj672w23qgcc8ewza0srpk0pc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T20:25:44Z"
    mac: ENC[AES256_GCM,data:5IEP4lQedDHA7etoVXjZAMERoVpHPp98T0lHczjEEbHPnkxBGuOu8THxbf9h/Ob60cB6Ysxeh+NTbo83D9ana55Y3304PZBUc6keMCPN53rlspL7Wq9Jhm1BdU3tWjXgoNDTRQuCj/LdFM+ouveJPNDUdjyNLmcNXrsVwfHDAnw=,iv:SKueZjopF2/rGMA5hTGNd37xa6AzvtVBd0a6FRxJkCU=,tag:jBuNKcD1YfuMWvXiclzDtQ==,type:str]
    version: 3.13.3
