apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:MIQAtfBOFag94NI7tgYSvZpNXy+U0Wl4XFcEyQry9kmk1X3yBNAmvA==,iv:I6c2heBV4tDLKfvF8n3LSepO6Eqh+GhNhlPAtqsJTVo=,tag:C9bRhuaAQXcWpqgMrft35w==,type:str]
sops:
  age:
    - recipient: age1d4dxpuyj8g4y5nd6pruueqxnwsd050rnphk0xk3hmse67l3w75csgdx0ey
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6OXhVKzdNSEx2SlJxeWhJ
        eGsvM2oyTW03TnI2SDNyMU1qQ05UU3p1dTNzCjd3Q2tQdkJVZDNqV2xWZlF0ZGg1
        Z2NtTndzeGJBbXUrbG12QmhHbngyUGsKLS0tIGd1aVpaM0NqZEpRbDd3UjJLZGVr
        ZGczY2g1a0ZieE1UVHVZRkloMXNzM1UKtcCvvT83BYCNkNTLIknAdUXn+y8JA/9N
        8BRdjAurpjvsUifDvpsNtw/m5TZMV9X38RljrXqPnBOS/PncYoj+pw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-25T12:45:45Z"
  mac: ENC[AES256_GCM,data:CwnflyiDfPvxnGEOnXAOEzLXuhkQspTvxat6lhyIIxhNnWGwyjUIoIEjScFjkMol3o7eb95NlULU88XI1DV4hT7X8UT8GAhGXStbJgqd0UNYsqSQVAMK8AJNqjH29Y2f7j688lXzePUCV6JACLYRaLeDEZJpQXGaokslzC67GsE=,iv:WrTNmByetkIXrztznh/21I5msfJE4RoMjRtC2bHaPnE=,tag:nelqWDigWFYQBhB+yG+JJg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
