apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:tDc+rJNcXES5juTnnYG9ETGEOPdE1HQMg9FejmcN12uYlaRhZYZfdw==,iv:Qm98GqnuvpwIc76bMWvVme9fHjUwGaNYHQ/VxHsyJMI=,tag:SKQz9bljUoDdaJrUcNDkHg==,type:str]
sops:
  age:
    - recipient: age1d4dxpuyj8g4y5nd6pruueqxnwsd050rnphk0xk3hmse67l3w75csgdx0ey
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3aGhiZ090MlNvbGJaaTll
        dCszNlZSNk9UdmpZMzZINkc4S0NveHBmTUJzCm5Qbng3ZHdlcXNocklCK2s1dkhu
        akZNWUJEdTJKTCtnSHo0emdnV25UZ00KLS0tIHJ3RHdJOEhKM3gwTW8zVWdWclE3
        dXNqbi8xWDNaNW81dTF3Tm9qVjFhTGcKPKWtdal6MhX11neZ5USnqsEu2KLbBEYt
        NCST1OzY7uMy8b5hY/SICB214CXVFZr2WrB6qN2IuihAB8YrREoNNA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-25T12:18:38Z"
  mac: ENC[AES256_GCM,data:OdoLhP1jYDCHMXqicjdLJpYNiXsF1KW6hEH22xIHf5iAzIKC6qj4/xA+pJ3Ur2iYIhqzpuorGAAnGVrcRQjXTFZUBij+tO2JjS6D8KD69rXCkxdzZ7vZ7QqVLZllMh9OgQtLv4jtPLr2N9tdyGdyj1/ia6HtlSBVip1IK+7Oo00=,iv:b0D3fRCP3/1Q6AYC4rJFOgVu0clsSmVcxmwXTdScuvw=,tag:Fc5HgOFtuBDtJthpApyBHQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
