apiVersion: v1
kind: Secret
metadata:
  name: agent-canvas-secret
type: Opaque
stringData:
  CLAUDE_CODE_OAUTH_TOKEN: ENC[AES256_GCM,data:flXS6v2vp15VParCrIOSF1awahBVKBJNa7TzCRTw30nLVarDAqJtoka0Me8VosltluS3tVit16KABteRIbqcGqtIOR4m9dROD1KD2m7vPt2ScIAZFL0kxZb0gVBNfAMOtlMX+PT4DIIT+eY5aw==,iv:zhwikkkk2Qen3RV18tlDGgvc87EYILxHbcbXJ8Pq5Uo=,tag:nIKfsDmpCVfbT9s+zxf8SQ==,type:str]
sops:
  age:
    - recipient: age1d4dxpuyj8g4y5nd6pruueqxnwsd050rnphk0xk3hmse67l3w75csgdx0ey
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4UW9XTDhvOW1ESTNoTGtO
        alNqYTU0cVFva0hHbVVVTGJsbGswMTQ2aUNNCms4emRYc3MzU0FBZWFjZnJXNGtx
        TlpCVFRlbWphaGFjY2J1OGNEQ2RVL0EKLS0tIHcwbnpWa3Y5TzFIU2dHRXJmdTJz
        dDFvQzJEVHBWai9OS1VHOGM3eU5PTTQKeeGTGw+Q7RwQMaFA4diJNVU7xcehKMqV
        SjMRRvXqelknWkWjyTshS8YNrnQWu92hSAfHWU8szSvuzHge5RprRQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-08-06T11:12:51Z"
  mac: ENC[AES256_GCM,data:P9c8I8Nr6JUNuYK27tw+1TR8CcaLobnBHXbyB6453lk7GYolHltKG0oOvQMbTClbhap3ZtVVbTasaZmGeALlx9++yMLC+cHt7LBwA2otLVbf+6SomBEaEwPWZDidSRoMmhlkkBSDdZTKduEvVLRKpwR5ErANyAIARISpclLs02Q=,iv:nHAKze74jq8wzBBkDPzDoIMq5a/wVEsWouMg8Hxytz0=,tag:T5G1LWX8GFI+7y6iggKrkQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
