apiVersion: v1
kind: Secret
metadata:
  name: agent-canvas-secret
type: Opaque
stringData:
  CLAUDE_CODE_OAUTH_TOKEN: ENC[AES256_GCM,data:NdqG1i6gebACWIv2vy5h8BJkVlIwvtu0qCy1UPl9c8Rb1vWgXivb0enhG2ucqP9O29JRdm4DJFud6yTd8kLXLnaIOtgMQlDEK1YhQ2MUZmYmf/MCUzUdeb1nvVF0M6NCDfm8/jriMXSicUZE,iv:z7zqyhYurLl95F5OwlRHTfYV86/uWsyXcfabT1ArV58=,tag:NdTUAL7vA//tQ/KnP2ZMdQ==,type:str]
sops:
  age:
    - recipient: age1d4dxpuyj8g4y5nd6pruueqxnwsd050rnphk0xk3hmse67l3w75csgdx0ey
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4UW9XTDhvOW1ESTNoTGtO
        alNqYTU0cVFva0hHbVVVTGJsbGswMTQ2aUNNCms4emRYc3MzU0FBZWFjZnJXNGtx
        TlpCVFRlbWphaGFjY2J1OGNEQ2RVL0EKLS0tIHcwbnpWa3Y5TzFIU2dHRXJmdTJz
        dDFvQzJEVHBWai9OS1VHOGM3eU5PTTQKeeGTGw+Q7RwQMaFA4diJNVU7xcehKMqV
        SjMRRvXqelknWkWjyTshS8YNrnQWu92hSAfHWU8szSvuzHge5RprRQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-08-06T11:35:26Z"
  mac: ENC[AES256_GCM,data:+O7Hb3YFBZOB5nX3/KoXWKTK48/2FK+XmsmsZTv1Bd8nKPwA++6EFvvSevHmwSE4ksTcgHWpPzPDWDhhK5twe7ohEU3ih3ty8H+eQ+Efduj2cncohkJqfAEfEcNyOLoXDGVwWp/XgpfAHbr9iaz3yApGTt8M7EpbCG4FqTcom4M=,iv:0d7h7XpjaJdX2qbTR36S8bI7nn68A6h3AuR1OTx0P6s=,tag:6pJ6lTzaXUS97oPCsiQyjw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
