---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app jellyfin
spec:
  chartRef:
    kind: OCIRepository
    name: jellyfin
  interval: 30m
  install:
    disableWait: true
    remediation:
      retries: -1
  upgrade:
    disableWait: true
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    controllers:
      jellyfin:
        containers:
          app:
            image:
              repository: jellyfin/jellyfin
              tag: 10.11.0
            env:
              TZ: Europe/Kyiv
            resources:
              requests:
                cpu: 100m
                memory: 1000Mi
              limits:
                memory: 8Gi
            securityContext:
              privileged: true
            probes:
              liveness: &probe
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: &port 8096
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probe
              startup:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 30

    defaultPodOptions:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        runAsNonRoot: true
        fsGroupChangePolicy: OnRootMismatch
        supplementalGroups:
          - 44
          - 104
          - 10000

    service:
      app:
        controller: *app
        ports:
          http:
            port: *port

    serviceMonitor:
      app:
        serviceName: *app
        endpoints:
          - port: http

    route:
      app:
        hostnames: ["jelly.${SECRET_DOMAIN}"]
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *port

    persistence:
      config:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 1Gi
        storageClass: local-path
        globalMounts:
          - path: /config

      media:
        existingClaim: data-pvc
        globalMounts:
          - path: /data

      transcode:
        type: emptyDir

      dri:
        type: hostPath
        hostPath: /dev/dri
        globalMounts:
          - path: /dev/dri

      cache:
        enabled: true
        type: emptyDir
        globalMounts:
          - path: /config/cache
