apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:UKdfRtQUhAsn,iv:QN3OliSvuTVWkAWH/6Qj+zvoYIZcJMp8euKb7mOlVlM=,tag:208oHTyXad8dIiT6CD2o/Q==,type:str]
sops:
  age:
    - recipient: age1d4dxpuyj8g4y5nd6pruueqxnwsd050rnphk0xk3hmse67l3w75csgdx0ey
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuTUt3a1ZQYzlqdFdLQVNv
        OXpVT2JWWE9BV1lBMTR1VmhNaVlDcEtkRVVFCkdJTlJKZ0dmWmVpVHkweVJzcGJO
        cmVXUjJNVlRjN1p6UGlraFBrTXl2OUkKLS0tIHI0NStSV3pyWFpZWVgwUWg0Zjhm
        SHpvaGVaZWw2NGpiTm9kWDFkUC9yTFUK5Yd0rQwECXuocZtal7bsMkouiY4GXHFL
        jjtzY8Da+LvEEc8u5y+UwAAtU3klfuCzDcgC92K92BNjfoY3dTW50w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-25T12:18:38Z"
  mac: ENC[AES256_GCM,data:9D9F2hZkXb6xgwrl9f+2NWLv1U2jYWAlFWFCzKYABtMOOn26kTxKGEd96vvcAQLPrlfppKXmX4FgpPBKnXzzk84RZbyba5MNAEdpNbvAe/v9J/EWGXrKKL6B2lBGGjy9irAd9or8WV/WCdwiq8rIQ3VQWJIykSWcBJOREtelnng=,iv:vcHLkCPxbQX4oZzR/ALgW1gG8KyI9eR/IiU2dLT5Rz4=,tag:CCVgm4/2PzXM8soGAUzyjA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
