apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:ed9vVeFp1uJa,iv:sA9pdqbwJK7OEqrTylzkdYnmTixX5v5tuDEqkDIlkfo=,tag:qZBvUawwDypMSboxtUllQw==,type:str]
sops:
  age:
    - recipient: age1d4dxpuyj8g4y5nd6pruueqxnwsd050rnphk0xk3hmse67l3w75csgdx0ey
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwYlZ5TEJvcS92bXhJM2lq
        WnNSQndVZHprUHJjT2FnSTdpUXBKQitYdlFrCjc5V3R5c0xUMWx0RVF0amVzcndF
        b1lsMXN2QzJGSXpLcG5meHQrVENZMlEKLS0tIDMrL0RQT1hHa0YzRncwTlZJK212
        Ky92ZlZKNmFkTXlvUTA3aU00b1hpa3MKX2ybBPtACD4N+9Q8BJio8pqoRzQYHoGE
        tc47TY/pGUJgrcsK+Ni/L2yVQfjDhnCCDxdBhY5bUhuetE1gMbLqJA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-25T12:45:45Z"
  mac: ENC[AES256_GCM,data:gQsFUSmttJ/jYSClCM3G8T+XAwqZLNwI8GG7DO9MhrMfpDooFGjcE3Sbj3QKgQympedd6/VtnyuIBw8D9VRqUcHWL0JcUXXvniJBHcXuCkeb/srQm8HrYunKOEQ2L3GBD7liXbce1FAt6iysBgd9d5eJln2JiC3jOrlBn2iisc0=,iv:FeLX8sYxOL+KvReN+mLBoXu3oqkYpfmSuAqb3EKYhdw=,tag:lDOev0qGDQYKfp+7OZKETg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
