apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:X3cPWeABl55lrTJ8islkBBMrZ1JIAZqWtfk5/94fm9M=,iv:ZZx51t9+EJ8eZWXxVlIcooXWqFdjt14xSXo/ROsbyWc=,tag:khUqQ3mg1XwU4HnqVYflgA==,type:str]
sops:
  age:
    - recipient: age1d4dxpuyj8g4y5nd6pruueqxnwsd050rnphk0xk3hmse67l3w75csgdx0ey
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVczJteDRSY1ZTM1hjUXQ4
        TFYwbTdydnR5Z2ZYczE0TUk5aHBMaVdaVWg4ClF1V2VBTm9FVVV4b25SdTcyTE9G
        dXpRZk1Qd3lueHZyb1VaVjlvM3QyNlEKLS0tIENaUTNwQWFsdTBFY3NzbVh1bjJx
        TGFldXBOR0dpZ2tRSlEzVnRmd1RMcVUKuGhQsEKsK/mjizXGlj+EDVArpTleQL6Y
        jXgxcRTIBKvZj+bXMtxV4ZiFsq3E7zt0WWEKxPTxTS15Z4cktGB1mQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-25T12:45:45Z"
  mac: ENC[AES256_GCM,data:FXM2jFq3nv2J13HPxotPb1uKvEgoEgbRwRNR/U64iyw1nKkTFgMun5ojCqwsQN8vbF90Tid2o62wVaRKZWOQsyfCQtyMvMOAuC2HOouzgKO488Q8+YmcrQ3J0xD1S8d/QRKcfRCpRUHWiDrQc6xM3yTcuLDJPbpjraKk620w+18=,iv:EhFC8dUvHqElcHJzx+R5ga1itiVdKfcm4FeBWS54TN0=,tag:rgfxvQENSD95NXdrW4v6nw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
