apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:wQAQF0FD3n8O2t07q68/n7Q06xAyzUnqJp8u8gb2EKI=,iv:fupQbd4Iei+ezLd0+ICa4hKMSOmLTNF3HRXOAV3gP8o=,tag:fCT1j5t8NYdmECuJWCw/zw==,type:str]
sops:
  age:
    - recipient: age1d4dxpuyj8g4y5nd6pruueqxnwsd050rnphk0xk3hmse67l3w75csgdx0ey
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0NHk2MFdzSk1RV3prbmtM
        YWFEa1VUcEcxaksxdEhLY1FQcldxSjQvWWhzCndJTFlYVTdoVW1yMzNLaXVQQWVy
        TURnWmk1dDk2UjkrcnZINUM1UkFEc0kKLS0tIDhGbTJsaGdONFkrRDZNS3VtWFJv
        L2MwWHJlVFR2NjM3c3M2QnNSREthRnMK88xjC8gCc00DK8Vkkp4rFstSmwLcGyvA
        EE6bGcBrProbXaspoOIfwJDeWZr3RygdWfwjnbHefBE08eB0peCSMA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-25T12:18:38Z"
  mac: ENC[AES256_GCM,data:00CekI0zEs9lJlRpEdcyvFlbtuiRkWGCwRxjnwT0NjrwQ7ECirf7o+naCrG1SddulVMJ+QD1noHFNTcO7jI2+olsV0UxipYaL+8cVCVMSDZmA9Px62+fwqYD6vTY8DoRnoxtkmx8HiTmTAvIPpY45x9cgYm9hxNWCQeHE6SjoFE=,iv:O4yQnSwBHSTsvjf5btf7c4EhZKRZTSqWJeR1Kn+Jf3A=,tag:B127ia5gdTs9MiOFlRupYg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
