apiVersion: v1
kind: Secret
metadata:
  name: qbittorrent-secret
type: Opaque
stringData:
  WIREGUARD_PRIVATE_KEY: ENC[AES256_GCM,data:s2n6G08rXeGJufG9merRwsOgPMYLkhLeDZG+5KqD6khNK6UNngwfjSCSRTA=,iv:1YwmXHjstPmY5mHZ2O8TSnxQj+SKM9eIzPHFGbY8W4Y=,tag:Ys92nflBP04i4NQ3U/1MPg==,type:str]
  WIREGUARD_PRESHARED_KEY: ENC[AES256_GCM,data:wT/eIS9H3Q/dX/nK0hrcndrGOnnc/TKfVxDpzJ+d2Cif/td7HtL0IRUVMb0=,iv:1mPl+sE56r3eJDYNIXZMpezUXVyUVGF5wBebqJmNb4Y=,tag:/gdw4Y1g7MY46kuqbsAIpw==,type:str]
  WIREGUARD_ADDRESSES: ENC[AES256_GCM,data:ytcdmQY5jXmZ4CVgCpTr4w==,iv:Tc5NdS3EQbJa5xzdkFKzKp5sNGOQPn+n1ZVUcKEqK9s=,tag:8SYLFnjC4fZcpX1o/Z9qsg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1d4dxpuyj8g4y5nd6pruueqxnwsd050rnphk0xk3hmse67l3w75csgdx0ey
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBseDkwV1NtT3NuZzZuMDBI
        OTdscVluY3lkVjRlWVFwVVpXU1NrSjlMSW1BCkoybUJOWW0wQWQxcVUvQU0rSVVz
        SC94MTgxaFVuQ1pOcU4wTlZRdHljSjAKLS0tIG12NFBRUVF1S3N4ektaY3IxMXF4
        bEY3WWljeUJoUnR6UEVVSWJYVFVOVEkKnsHg6k9qBn44TR8qqgEKjRHy1Gl4JxZV
        5wXkWRnjoHnriccdsNjfKqCKcUZ+hYKyTb3txJMeezdTIirkcl8a9Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-05T20:39:58Z"
  mac: ENC[AES256_GCM,data:hhD1EHNorfE2/hEnLB3hLXZua2+aklQSKvQiEN5H9fmlcr1csnjzT+/kmO6kaqRO7tSjGHK+rXSZ4/cdojJxEudZBmpbM1hIqBkacKm+rW2jDzJR/1OqC0q4gUUOEum7qI2D4RgGzlqz8s0BzuiSceyQqUh3hswPk/C55Y4NgYg=,iv:mtx+N9u1zzT1qANH9eUkIFKDgGZG2W1zEUBlmY+9ZiI=,tag:hhn/KIU5/LZsYZcShhjadA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
