# CNPG needs the role password in the database namespace and both username and password keys.
apiVersion: v1
kind: Secret
metadata:
    name: aiostreams-postgres-credentials
    namespace: database
stringData:
    username: ENC[AES256_GCM,data:C/QWfpX6euoGnA==,iv:pw3TvZwEL3vB6POejYTD0oSo39fU9w1ZObJuTqlzLWs=,tag:TEmG22MAClB4SAZAsII8OQ==,type:str]
    password: ENC[AES256_GCM,data:GPMBf9fld+Gbdpi3tHZbK5oLHqSIgaJjZiBHuwKDVxQYRtPbTKDZasYHR/Qdn6Yf,iv:foh2LiQKhFtLudAR/QC1pdEaTuwARczeyU25WcKNlto=,tag:KCtujCQJy8zuIff8NFdICw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBERTlIK2k2bmpianNiZW1z
            VGRmcXpMNDNObks0S0YwaE9ZM29oY281bmc0CjJJZ2JidGFBR0ZsTWpKQ3dPcHpG
            QkNkQnZqMG5OV1FoMHVoakNhcEQvMXcKLS0tIG9FR3JEelpQdUpwQUh0SWc5UFFU
            MFFEdmlRdE4wN2czQTErTDJzYUZIeGsKw5LLOxyBK9CrUrHJqtLqTvB7hiSg66oe
            OE0t6nW2lhWjx4qBKXvKMdD5rJV3cnDWcDboMm5FfZBPf5TxD2m4fQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age135zaeaxu0elyxn9ax64dgw9hsxk2frpnqpj672w23qgcc8ewza0srpk0pc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-07T11:18:16Z"
    mac: ENC[AES256_GCM,data:RyPQnh9oa6dCvf79gIP12ZAdW5ICmIpEo1Y+bRFWQ7IRlyoPrIg3zTjMKHk+kv5jdijY8qx70gVH99n9fUKnQq5V1f7VzgID0wUjXCPbjHBSHsvPWqZMZxNVlZsHPEiKBPmztuL/RgGrugoR0UHggdpegj+QI2cuaupXY951Ysw=,iv:cYT7PuYpmxJwLkuiaCGF8Y6fc1uW5zHV9wzhCc2OC/g=,tag:PVVoXTqQ1Avj3Y17AvXTRg==,type:str]
    version: 3.13.3
