# Separate from the CNPG role secret because the app runs in default and needs the full connection URI.
apiVersion: v1
kind: Secret
metadata:
    name: aiostreams-secret
    namespace: default
stringData:
    SECRET_KEY: ENC[AES256_GCM,data:RIUCNKoLp/mDAJqe+4YKROnNZa/vdbiOmfrPthMfFUPIr8jNWv/n5VWMWybEl2p3+Po51Q+WkwJnh5Y9AU0XcA==,iv:ULVQRCm7phEpjVpHBItIfHtXKcZ9i6v/t5uAyFxYd1M=,tag:oohUT/BHVBq/oH50agY4qQ==,type:str]
    DATABASE_URI: ENC[AES256_GCM,data:+PC7PWi989a8o/Wue9cPW7caEsKJrB5S8vZxTgALGlsRbwQSZ/gzNjzbW6VxmH2nfS3kXniUMKXX5oUOZfKKeNlwxZqwQl9QATJPidigGXYBm0k3KN6a0TDFfhR+r3YUjAytO/nPdMQBUgeiUZ0dkAe+F8lY3a/JIaLtRKI=,iv:wkaFRtFwaT+ps1cUEYoJIL8t11rFA1B7LpGAbT0M8w8=,tag:0eXFWLeDcW+YAYPljfQb4w==,type:str]
    AIOSTREAMS_AUTH: ENC[AES256_GCM,data:O/Vrl5gsNVvx0NqoSbRGufWPZxNiw6PRiV3mUB3t,iv:KGUeqVJrB3vEDwr4N5IGy/kgQy5FI60VcLeUNqDEB50=,tag:I6TEbf63z9UdId69NVwOuw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKN2xIc1o4TkNTU2ZwdkxB
            akJNOU5NR2sveWVRcjIrc0FYMmFuNkJTMVZ3CnlrdERXc1VvSGcrL3RrY1Y1QVdO
            U0FNaHlLNS80eGdreWdDYjVFVk96eXcKLS0tIHhmeVVtS252aitGcW03dzBkRnAy
            YlNjV2hLREtTZzVXRXpZZUYwbFR6RDgKMcBmf7VLzQdmInc2pttaQG4ufqMPj2F7
            3bZIIiuqAk1pgSSeDvoxJDLxTNLzSUabw9Wl/sbrNariwQhQjibJgw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age135zaeaxu0elyxn9ax64dgw9hsxk2frpnqpj672w23qgcc8ewza0srpk0pc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-07T11:18:16Z"
    mac: ENC[AES256_GCM,data:1AV2TfABT9xD1YJwZLy62W1YRMQq0CLpQWGigsoX5Lzvcd1N7YeoKBpi9IrVQoZ08Uquwhj4MWMHiIwW3m2zPxW0JZHkIurg/onajtvNYH6EkEV5Z874aPGcGORaiPsybZTHqpVSeKgUK6PL+g4CDaAswTA6mMeX5KvwAIFfiNw=,iv:E0sU21nr5Z9aSpfLBvodTIaLXl8Vc4lrRpDf1LSvDkc=,tag:TOhSX8eu8/bdaiRimQGAaw==,type:str]
    version: 3.13.3
