apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: cloudflare-ddns
stringData:
    token: ENC[AES256_GCM,data:cQfHzzX/ATVzAWiB8GHK6rVKABila7hnE0YEK6KCYKpZ7dpaW/4LDqoFb7EVAilp6smuw20=,iv:YSd9vH4wVnLDK6LMzbC0bKwTRn4ZN9b26+mF3LzYH6E=,tag:5Ze7SSbJKrh1xMK76Go2Ng==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0eUtpNTRwOHJHQ2QwRmJL
            d0JLR0h6TUEyZzBzai9NSmMrQkliMDBKMGh3CkFBYWR3d1FJSEZjalQzQ240NGxy
            Zml6bkc0MngvQ2U5UGt5KzFsbTRoOWcKLS0tIFROUTMyOEdoRTI5akRpWDQ4NW1C
            S2pzd3lWbXR3dUlmVVR0Z3hiREw3M1UKAyNZF3DdGeu945hzmz06tS1sTFx+Vvpg
            O2kpfe7X2XPqVWJO9ECR3ZxDbCN6iSKXPpU5TdLABwiDXmyGeRbKiA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age135zaeaxu0elyxn9ax64dgw9hsxk2frpnqpj672w23qgcc8ewza0srpk0pc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T13:42:07Z"
    mac: ENC[AES256_GCM,data:ECyf4nP3CkJrpCmToZTQnsjpoEbXgW1k6IiAWlrP7EnSJisP7mkX8aLFK0Gv/EoP24Os4WKtMgQlFknqXj782yUBFG8eEI53vAgCySP6+/Q5qGeid+glyHKpg5Hj09+9nJp28PHK51KRuOPs10lbY+qOrd0aoIfilfYZ/0pGcDQ=,iv:ibW4mSNNEU9n05tzFJpu4NEHABG12IpjQpZsIRBEZjQ=,tag:f0CHZTSDCoNG8wzexEqZ6g==,type:str]
    version: 3.13.3
