---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app flaresolverr
spec:
  interval: 10m
  timeout: 5m
  chartRef:
    kind: OCIRepository
    name: flaresolverr
  releaseName: *app
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  driftDetection:
    mode: enabled
    ignore:
      - paths: ["/spec/replicas"]
        target:
          kind: Deployment
  values:
    controllers:
      *app:
        replicas: 2
        strategy: RollingUpdate
        containers:
          app:
            image:
              repository: ghcr.io/flaresolverr/flaresolverr
              tag: v3.4.6
            env:
              TZ: UTC
              LOG_LEVEL: info
            resources:
              requests:
                cpu: 15m
                memory: 150Mi

    service:
      app:
        controller: *app
        ports:
          http:
            port: 8191
