apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./app-template/ks.yaml
  - ./whoami/ks.yaml
  - ./zurg/ks.yaml
  - ./radarr/ks.yaml
  - ./sonarr/ks.yaml
  - ./prowlarr/ks.yaml
