apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:UrdLbcpqACvZ0+0jJkvG5TvEosjvabfMu9Ga9Mo6b5V9+g4RNlLtKpgijTNSkCqlRlMPW5REEJ82Uglz+pfKqnqPt6JkPEx836O12zdBF++ic4REJ3H2BdD+73t+OxOHIopkQc7ogwCFi36esH4bEnPuIxmD7xX6XOFhi0AHEuxhNMwF/e2ZBKiSmoSLUwo1Qdv2Brsubk73TKOIyjdL8MWRNuGqupRCyg5vcjAoFxmQCvCL,iv:TMKgLawUuFTyBnzZ4hhSnLWEbK70MsXIMognme2hRvI=,tag:yxE3X4FKYu2hgSeoZsjfNg==,type:str]
sops:
  age:
    - recipient: age1d4dxpuyj8g4y5nd6pruueqxnwsd050rnphk0xk3hmse67l3w75csgdx0ey
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzOFA3YUY4TXEwTThaeS9i
        T3RVM2ZCRm1WOERMYm5BdHNXejdpbG9BclVNCkxyZy85N0tKN0RtSitZckRhdjA1
        M2cyTWM4Zks5ajFmMzhtWGlYSndONTAKLS0tIDNqNE1JZ2xLcnU4UThSUTYxeDl5
        VHB6Y0pjWU9WQnZwTVVVZU1KTVhWNWsKZHEjJ22V8GykQEC8kp/4CnsJKmn5Vld9
        mrduLJUkGVckTOSU9ZgxNk0cQR3eCYBy398WrKZQPclUpOP3lGTT5A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-25T12:18:38Z"
  mac: ENC[AES256_GCM,data:ThYzG9XbE4K7F49bX5xSywdj9WaACyML71J5l7ZrR5BLD4xsjuAhpNuYhyk2qIK+c1LQ6EHwzddjqtLDTqciqRmuARaXjOzQ4ZmoLNRyyx3jnpnudJLSkpVMS1eq+w5ZxUC7RaHoO2nibEEgKoSPEoK4RvkfUx9Al0YafVzw/6M=,iv:70DSAwcD2QyQFrAS+AF7LpAcoqq6EWjtYM8JRBK3SNE=,tag:7o0EI5byjZ5Ce5udu9ny5A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
