apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:vnmQtxWYWpBFljdSPWMzLaYYyI0kf6RM1DKmqJ3THuWgLv51j0GnNin5o3HRrc2f7L0jD5IFPkFmkH0TStWy+PbPt4TbGzJxGFX52kkHl+6opSMuhLkMHPOGPrwRK4A+ULGb5pFdTbQMgRVfd+pvQZxXr/mt8OKBpjBoTj1NQjhJvuXd+XSUWpgqjzrRlUs8J6qBh3r5OpGjMfXSQ5krtcJqueTu2WFIS5uAUmJ3Qmws+ATe,iv:GFbkpHz++lMI3MikBwlcpuCmUzVs5tB8gME1UhaN3w8=,tag:6YZ4eAbUdSW1vQUYt+CGhw==,type:str]
sops:
  age:
    - recipient: age1d4dxpuyj8g4y5nd6pruueqxnwsd050rnphk0xk3hmse67l3w75csgdx0ey
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiamhabzVCdlZWL1ZZS2Va
        YUgwRndqdlMyazlXRjhrc1VRSmQxTHpaVldrCjJialRCTlh2WHBqMXVTemxTbCtZ
        bXlZRWVWQUYzVmNaRWtrM0k5QXNFbFUKLS0tIDFtWGlZdG5PSHlsK3pHMjVnYU5x
        U3hpS3ZkNDdRZHd3dTQ4SGJpVFhrU3cKDzocaXtnrGloAzzsKuv23DTBoxjdlOvK
        w2Aa31Pvmtu1GhP6QNBurOr8F0vfg5Lv5yc9d9bLdUs0ET+XJ+Fsaw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-25T12:45:45Z"
  mac: ENC[AES256_GCM,data:RL3QT7hKa0WaYKtX2SzxPmg1IuaNZ2eDx4nkaxnVxfMPRorwSMkOc7/HouECt5qrxGKTayYnLmUhVpUpAgDOBrdWKwL5gEAYJriED/mlNhA0L0GBehjHEI/VRYKq2DQwFhUJ7zMNvAEGWn7tio1dLTTEjx+ciZ5ueWfMd1cdME4=,iv:5F4O0Try2XgsmjsfXWZX9DJ35nAtDb9q6HwLh35UAcM=,tag:JmcziuvpGnGK3VJ5GEhPmQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
