---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./secret.sops.yaml
  - ./ocirepository.yaml
  - ./sure-db-helmrelease.yaml
  - ./sure-redis-helmrelease.yaml
  - ./helmrelease.yaml
