apiVersion: v1
kind: Secret
metadata:
  name: sure-secret
type: Opaque
stringData:
  SECRET_KEY_BASE: ENC[AES256_GCM,data:PswjTdZYnO7OmB2ejShjUVtC4oM+SH6G5AzFWgmjCAgM4Fph/iuDlmAWEgJEyeG3CMJX2kAXabOcYNzgdLIie3U0sHE6O431ozBD/jKT4iUAbQHtmYhHbEQakhkZRzfW4UprdJEEXHfcf2BBwEEW0tUANOfXfZ04RBZlmtE/9Ug=,iv:gcUILSBq1vD0KcgTBMrhhPxrwMcTM9HXJdaujYyShs4=,tag:Y/LR8UuOKngq+Eu2VX1FDw==,type:str]
  POSTGRES_DB: ENC[AES256_GCM,data:3Zmf3zTKfBUF5n2odXgg,iv:7DRxo5/AECHjVzZgSM28VCAaim4kQUbd7b4kx0ToIUo=,tag:1HFhQKUOHgJALDqvJORgdQ==,type:str]
  POSTGRES_USER: ENC[AES256_GCM,data:OPqbdH151jWf,iv:K/jWQmkvQiCmpyVkfyodJAuZWdNilf5iFhnC0s1Jgiw=,tag:/30Rg/OXZN0FEtl2SWG/0Q==,type:str]
  POSTGRES_PASSWORD: ENC[AES256_GCM,data:kCbG+Z0w3UbmlKXvF3kiTg68cna2BZPQ3XkifUncg7k=,iv:W3FDwaT9aTIVI5BSQUpKuIP3VBCHA4Q5iXnMUE3gpi4=,tag:UeIGUtaFXCmJqsGOEW7fnA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1d4dxpuyj8g4y5nd6pruueqxnwsd050rnphk0xk3hmse67l3w75csgdx0ey
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpUkF2YStQVXdmb1EzQjlj
        dTAvT3Q1eCtDOGZ3UkY1UHdkMGwyRFBpQTMwCnVudzVTbWNkSFVRYkQ1NUNhVWhF
        QW9US2JzL1Z1NVJJNE1mbHlsaVl6SFUKLS0tIEpYenhRVVVIMFlCMmdMb1FOQUNK
        QXIxTytrbmMyTlJiR0J6MGVML1lkcWsK9GO4N5jUgp4mJLHTz0FhpCumuLxsAql5
        rJFwSJACv4W4BTSBrVD5rPXh7B3M/pNT3t/ML0KuyqrBo9BrxIXXww==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-01T20:27:41Z"
  mac: ENC[AES256_GCM,data:ylY4mxC5ALSAfuh9Lae45Ewr8OPx+2d8lP1BQDVW9Z0djN5/E6f1TevxoVbITdUBHQfYFFOi/My5vtuBc2zmw3tLCRINxYEaIOvRRK+K37mH+i05PLIJ6S62N2S2I0W3o2j48oT6UAx7dNmtnHz+92lhpm0ul2ZkMrrWcbTayNI=,iv:JdSxzz0mxwQC7ykOMMRe9GvCuI7G0xwDEEu/p/9ljYA=,tag:0XlsPsyyn4u4PowpzbznCg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
