apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
  - ./httproute.yaml
  - ./postgres-role.yaml
  - ./postgres-database.yaml
  - ./postgres-secret.sops.yaml
  - ./secret.sops.yaml
