# CNPG needs the role password in the database namespace and both username and password keys.
apiVersion: v1
kind: Secret
metadata:
    name: seerr-postgres-credentials
    namespace: database
stringData:
    username: ENC[AES256_GCM,data:3L0S6DY=,iv:kDPNFUHzNbYOtLSyVhJKT/EeITYfBO4S8pvoBGnR9/w=,tag:9mMZHXyutLySxqy1ASLEfg==,type:str]
    password: ENC[AES256_GCM,data:FIf6eDotzL/mwORnAbsi+TKf4ssgNAiMN2/GoRwKVPjRBPd9Ro3fdbU3SwO27Qr+HK63FHgApOEUQuBD4TyVwg==,iv:piUyST5rsunu5ktBo+G64cm/0m+6nz5QLJPzz/F2UGQ=,tag:tbiD/GlxB89+Xj3T9Hrx7Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLODlGMlF0L2hsUVhrS0Ra
            TGlHL3NzMk04ZS9mcGo0VlBHQ3ltNGRlMHk4CkJQQzlQdGVsTHVXVENlYThUWUVZ
            bWRUTk1ERHpVbWpMZmlrUmJTTC9xbGcKLS0tIGsyYnpVTEsycmFRejhXb1VZOU1r
            UEFqRzQ2VDFmYjJOb1N4Ti9obnB3aXMKOWzDlOuIWbBn9oob/miz8G06uLTwGVA9
            L3BiyyhvNgZyJyncEjSYYWioRxORD5Bs3WyR7ot2oEwMTGCTMiMW1g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age135zaeaxu0elyxn9ax64dgw9hsxk2frpnqpj672w23qgcc8ewza0srpk0pc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-02T14:19:30Z"
    mac: ENC[AES256_GCM,data:QvFz0gscylvAkmYCEGvYBvpHego23sPqVRvwoceQu5h5jMoDEVSQTfxUle4OdCG9GxTFw7Bb/zrKnowcv5YhggPKkg0jkearTix8mwYHHYVrpFZzjooxTv3jXCMvS2zQIlm7yoFfjjzdz7k7or9SP2bu3dDJeNNGNGlFWMrXSJQ=,iv:+hK0rYmEXfQbf2sWjmk53355pW49XpNKZx+bb5CpmXM=,tag:JTBnheQWsGBxO02mTeyf+w==,type:str]
    version: 3.13.3
