# Duplicated in default because Seerr can only reference a same-namespace environment Secret.
apiVersion: v1
kind: Secret
metadata:
    name: seerr-postgres-credentials
    namespace: default
stringData:
    username: ENC[AES256_GCM,data:zG6s8fg=,iv:En2lHPmv1AWGvh6XwfIp1YCRNUcZ7edxJQvSxpxrLU8=,tag:DTdvJ0z/SXQOpooTsZLsTg==,type:str]
    password: ENC[AES256_GCM,data:b7KNL3ev2QMZmRp9Kr2G61iZeF4Iy+ioNSTXS/5TIRGOfGESVqwU32ZfYIZZSJFHjIhUj6itdS98EFwQT3Su0A==,iv:eBw7VZ3Hy+VWl3PDxxr66sFZKyMvdrWgAXoo9ZxtyKQ=,tag:ldlbGTj4rmJQll+Mu3yXZg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMQkU2TlZGTlFOTnR2S3hO
            cU9IYWlJdThGMW12T2lTTlNpZUFzMjZRSUJFCjhBWWJiRjVqWXJUUlpKak1BbFFw
            dVBhY3RVYXBHMmdsRGVuczJTbHBSZ1EKLS0tIGE1Tk1pS01zTXJHcHYwOFJQcmwv
            dGdWaXdUUUhhUFcxZGlvbld5VVJCZXMKiM2Qr5teMM1DRRo+BT1TNId9VM4D285T
            iD6kodVNlSKNrdD2oAi2MU1THAY6UiC2l5Pk1C47/jq2V0AtdHfYAA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age135zaeaxu0elyxn9ax64dgw9hsxk2frpnqpj672w23qgcc8ewza0srpk0pc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-02T14:19:30Z"
    mac: ENC[AES256_GCM,data:4u3k4wxnQqwFtDv/c7009AMghGbRlCVYWSTzoz1pw+/vFZXb4Gh2NKldG/usbkLfvPqiuRsjkU76qSCTMy+ExtLg+fHiDXE6siEMf3975bw2PiswVt1lwF/f4ytChIj0L+GSvluV1y69vOiNqH/LxCHP7z+RlPMPaFlwELNv7nE=,iv:JI2k/E+MOQso3aQT0xSINz+akwZRe9MSspAIfRPES40=,tag:RaOoTPyJ8KIJr3u+UKWwrA==,type:str]
    version: 3.13.3
