apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-dns
  namespace: external-dns
spec:
  interval: 1h
  chart:
    spec:
      chart: external-dns
      version: "1.x"
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: external-dns
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    provider:
      name: cloudflare
    env:
      - name: CF_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: cloudflare-api-token
            key: token
    extraArgs:
      - --cloudflare-dns-records-per-page=1000
    domainFilters: ["jenya.lol"]
    policy: sync
    registry: txt
    txtOwnerId: serenity
    sources:
      - gateway-httproute
    interval: 1m
    triggerLoopOnEvent: true
