apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token
    namespace: external-dns
stringData:
    token: ENC[AES256_GCM,data:FGcy/s/m73lB3kMMDEM4nnHlcO2AsVLWLgLaEKaMdNXIRsweWv20oNqz9RwVu0Z3To3yyHI=,iv:TpJqA4CuUAXx6z6QiCEJbB/MUsBNA/hJYp+YeZb3pMM=,tag:23mE5V6U4ZjH+vLG2pen2g==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDZ1p0cWVQMUJXdFpBZHZD
            WldlS3U1SlloRjZ1WUsrUmpNN0l0NG9kSEc4CmdyWDlOcUlpcjZGQlp0Sk1zTHlE
            ZndNTzNuWjlLTlVKVXRjZ0g1RWIyMDAKLS0tIEdNK3l2WnpyZis0QnFlZ0FxY2Vt
            K2oxZE5IclRJbDcycDJGNGJKRVZuejQKy6KlBdwUKjZeL9RHbGpt2LxZUI3BCnpS
            lBL0ixyQh93V+ZVQZgrF9dK+D6CaR/t4PB5gtmqVDtXyqV1D4B6VnQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age135zaeaxu0elyxn9ax64dgw9hsxk2frpnqpj672w23qgcc8ewza0srpk0pc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T13:10:52Z"
    mac: ENC[AES256_GCM,data:iu+Ez4uql6ea7o7hnOPuyIHpIuxC3wuF4fiPptAyhb0nATMpZ1r8gPdvx3zkygG3YlQyMXMkHBqrpRwqO6/ht3PIVK/Ult7ipV4dPE2AQzfRVONyBDV2TBnMHe7xAOlKcgRC85U+G7RmouP9aI8/HLqlhf5c8YQEnarwyWMuK00=,iv:NVBXBfaLaVcjfWudEgzllyRHxELGSmFqkh42dT/6/Cw=,tag:9YaWDWWk4xKD7nzQxNMu5w==,type:str]
    version: 3.13.3
