apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:ZdtRSian43e25oaKR0CFH4efIJP6gcNNNndK1ARhopNSnktjZLKwxw==,iv:m3hhZme6pXzUj/Kzl23W3K8nHHopWT+PiZMIZ2a7gGg=,tag:whXg9Do0ciC0yd1qHkb6PA==,type:str]
sops:
  age:
    - recipient: age1d4dxpuyj8g4y5nd6pruueqxnwsd050rnphk0xk3hmse67l3w75csgdx0ey
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPcnREdlVOa3ZXVWpSQ0pv
        Sy9sWjZ0U1Bpc2NiTDJsQ045S2JJT2c1Q2tzCnlyVlBRbGRtRDR5SCt1cWFoVlg5
        UEdiVjlqYVVwY3Q3SGlTL1c1Z0JaUzgKLS0tIEI3VnJDejBSY2RJNEVOOVpPaHNM
        M05YOXRFNEErRU1QaHJDQ3FqRVM1UlkKH1PAiPisqCofmhBEMB2JQRoOtdNemJpb
        1PlpFgK1KailLnr2vFVjoFZaEfP3GGwLTJ4x+gZRDmo36PZNlGBsew==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-25T12:18:38Z"
  mac: ENC[AES256_GCM,data:LpIjEe7P1gFwpHIbjSgzNZSqoZfYReRmzf5UXrk4I6nRxlk0HmChVJxlCFwGtRVjw57yLX5fgWXUWB11QootaPl8Z21/zZo9pcWavkrwxrOcsvFcbSduCyYfTyzvUeviXnIhTECsbxZLBkmSLAn3AU5tUJMPM9jPNWZFE6PP3yo=,iv:skNeuUf0yA+VHi4ldOLYS1eCdL8JnV3uNWS6sOWkbOQ=,tag:vGOVZoHH+l3CYHP4S7aYlw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
