apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:sSghkASEXVx9IzK8mdnspLHzFEYrYE1yCtjmVBJ6ACJgEK2+aA4gaw==,iv:XGJGCQRgfMXiXPL7iRdM8acpthuTJSTj75z2+VGXk6U=,tag:yqpY1N03zHnlpTXaXuyehw==,type:str]
sops:
  age:
    - recipient: age1d4dxpuyj8g4y5nd6pruueqxnwsd050rnphk0xk3hmse67l3w75csgdx0ey
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzUVRVSG0wZFhXWnJaZWJN
        T1V3OUNkMVEzT0ZONG9CR3pWSkU3MXZ1NkJVCmNmVWE2T2pCVWFGTytLaG1ZTXJr
        enphUDRqRlczNU5keGhZQktVcnZISWsKLS0tIDd2aGJVSFg2bEF2cDg4N2ZoM0hW
        SnVXK0E2VDBwYndUdEtpWEJSVGVvMUkKjmfqGjZEwDAuSa6TNM51Nt34WQABOlfy
        0Kb/0cIkpiskuRINrEWRfavPWeHFP4oqLE1ehGm9BRrB93nKUD+u6g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-02-25T12:45:45Z"
  mac: ENC[AES256_GCM,data:i6uUGIhyn2vl3D2zakY0nODYgFKTAfHdMTJiZZpTVO2PdVbcVTzft2Yj5V6WBoknUFbZHLOYCwsw7t9K5aXQBx5NJ+cwSqEhuMSMf76UUUS7qWWhkM7GqOhESslnsAnhpmOWd7N/wnZzEtu2nmMzLcmz8HZMkf99chmU4GsdtgE=,iv:SCpCgb4PV3bGnWgjei5AGQSrRHp+2QaiqVprm1OCI0M=,tag:A8USVtsXompSykk2x37pOg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
