apiVersion: v1
data:
    RADARR_API_KEY: ENC[AES256_GCM,data:g9b7NXvRW2DgAJ6OqQcC85QKSf3Tjvxp+qt99+R8cMI94EhtqyktfrbM+is=,iv:iC4waSSOLgsc74tBP8quGNSkWeiCO4GmhlTyGAC8OYo=,tag:2hGZL56nXjRjfqu5nZ4x6A==,type:str]
    SONARR_API_KEY: ENC[AES256_GCM,data:uvuSdbCm/4L3KdvyhQzgezsFQmbF83hzVQcXsbVOu3u9jBE5oVrbcYoTfao=,iv:mqON6vHNmnTzqVUqBJe8ON4WsH+DG3fdHbmZM7mttDU=,tag:MXLDs1N5Kb0SkJu+2iXLXQ==,type:str]
kind: Secret
metadata:
    name: recyclarr-secrets
    namespace: default
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwbDdlb3JRNXJTNjVXTHFk
            NzhiOVNPNWxZcmpTMzJwbEg1U3RJbnBvQkE4CnozMmtHcyswVXhvOGNRNWw2ZUZj
            WkRWZ1l1SDZFOHNmVnFLQi82ZldVUGsKLS0tIDlsUUs4S0NNTE03M3JsRTV5TGo0
            R1Y3cHkvVUFIcVpTd3R6WHZQZHZTYnMKnhx2DWRW3uASWm+dQ+Ha+QVEWDOtzsTp
            rRHSpRkhPnq6R+ESJiMKaT5Pjzay4S74Nav/FvGVMjLa2LEfpQe7Pw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age135zaeaxu0elyxn9ax64dgw9hsxk2frpnqpj672w23qgcc8ewza0srpk0pc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-18T07:30:20Z"
    mac: ENC[AES256_GCM,data:MTBpxNkM/nms2M3rDRhak7ZecKZKBYKkOK8AA2W+RbjZzPPD+M57dBVmkVsKtg6M8hYd6wz1zc/DcV/OAHITlC0oLZ8YYvv2tuIF4oNRbz4E27qkDOCNlKl8HofBUOi1+2ZS1mtIw9n/+RVLT2WK6HI0vBHhXRate4ySvp/rh1U=,iv:YDwKx62MBLGmoM9VcaHwpTPRoHOaqgDHqouN6pBNbQc=,tag:ygHaiqemQR8LtX61uF5R9g==,type:str]
    version: 3.13.3
