apiVersion: v1
kind: Secret
metadata:
    name: webhook-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:86cJTFTTzH0HRESK+HmU5SNk2pTL6f/ofbPyqRG9hrJfPtlUbTCJ3w==,iv:SGihBXDSRjwPTQAHJxQ3o0N5UB9QkT0uGLLhY8ix9JA=,tag:Hggq8eMLHG6ScD2ltQz3iw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0UmxoU2ZrTENoQmVvWjNF
            Q0FaYWREZzNvbTVVdEJVV3ZtSmw1VkV0aWhzClZZRUh3bnM5ekFacEZhVEhqb1kx
            YWZrM05Tei9iK1hDWHdaRGM2WGpsUXMKLS0tIGM3NEtaSHVBWFdJdlZqd3l0OXN0
            dWNXMTE3Sk5mVENOaUc0aFd1QVVFeUkKNMegt7nyLNWdMi9U4PXMQjfKgztCS1X9
            4D3EvY11tt3f4THIPhQ8XmwZxkg6Lrhfz59cjQLltQpaYfl5L13QlA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age135zaeaxu0elyxn9ax64dgw9hsxk2frpnqpj672w23qgcc8ewza0srpk0pc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T13:43:41Z"
    mac: ENC[AES256_GCM,data:uxHw8peifOZV9e+zOhjmIUvpPndelUhT4G+iRJ6cXjaQRvVLrW/9g/oeBkEgMrrU0PjyEYjmp2VFp7RnfNbQMlK3adzseYISYeeIM6DO0zWcKSeKpVwd07O/vgEklzCIWaTyBQbzZTk/DpQHJqSPIAtiD8VXQt/P5kv0XJFVX/M=,iv:FWqZ7ZyzzGZ9nSbUCCHtIsOZQ1Mbpe0c2+tSkq+DBBo=,tag:b+wcYRXys/J4DTkG10kRRA==,type:str]
    version: 3.13.3
