apiVersion: v1
kind: Secret
metadata:
    name: pihole-app-password
    namespace: external-dns
stringData:
    password: ENC[AES256_GCM,data:Edlhgk31VtDts+gbqxHxMENhqs1zkU4niJNkkdez1lp7/Upwytr4fmKPET8=,iv:NR3e39QQ9ezmhRnASOF6U0KKVwtn5cwQP6QOkNo5Tbw=,tag:1XtAxfodB6vkqmJ6fHL/+Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCam9WeEJWb3JMTURDWDF3
            WlRmamlpejRweVhOd0Y2TTBCc3dNTmVhYWw0CkZMM2F4VmFKaTdPd0FId1B6cWMr
            WGFRclRyam1IVUhYV05MOWpSYTZyQU0KLS0tIE1WcmNEd0tmdCtXaUxianZYbWpx
            bDljVEhsS1pXUTFlR2s0U3FBaTZZSUkK6PvPPZtxKe8vbjo/yPz73o4Ec7vhkfQw
            UBaqtStIrm1Fi8Ds4w7wbXV/x1J8Jw/lV3cxRshi3ZN7oPpovclWtg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age135zaeaxu0elyxn9ax64dgw9hsxk2frpnqpj672w23qgcc8ewza0srpk0pc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-17T14:19:25Z"
    mac: ENC[AES256_GCM,data:AnlW8YYEtDIzA+p0wmcLygKFV2sA+CFPkSfVZHZAqKGWBFiEqpqB8UCF0CY3L4kDhYg5TNbKpxVGuKNJGZe6+OMHkTnqulsj5NV5Aj76qhdgujq8qVLwFqdoKAURZE5xA1ayLGdeHzbtulWdClsuoEh1OaHIB/OTTfZC+yBi4Fs=,iv:nmopU+B1eYoT+uISkDGTmZ0Aq/eggC49ttam0bBmlRQ=,tag:juSbfjADgBo5w29eMgSyJQ==,type:str]
    version: 3.13.3
