# CNPG needs the role password in the database namespace and both username and password keys.
apiVersion: v1
kind: Secret
metadata:
    name: aiometadata-postgres-credentials
    namespace: database
stringData:
    username: ENC[AES256_GCM,data:WBYTI1j4PQoreeQ=,iv:3DCKHPuB/YzL/rXba8e1F1VCgLEVLVMSklCkaTAdbUY=,tag:rGoOHtR23b8mgJrayzQi+A==,type:str]
    password: ENC[AES256_GCM,data:MVmEZUHdklB4dUAoVqW4u6klmUyA7OAFht0B4Z3ogbdrcf3YA1ymTGvrwdjTtUWY,iv:rkT+8S11MhVOGvmuvn8y0Nca35KeH3AQSe+S8mzV3co=,tag:ukP+CKr/jIFFSbhx4xkFQw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNTGZNMHVpUFV2MHlHa09X
            MDIycVlJUmwwcWdqS3gvU2JZQzF3QWJySWtnCjRqUnFNaWI4eHU0UEdhdHVMdk43
            THNpTjlRTmt3MTRSZVJGdVNORG5xTDAKLS0tIHdqU2JISy9yZ25RYTFCRTcza211
            cjFKK285azgrRDdjRjhUbm5DVUwyRzAKdzt+Bk0dzZ+2Q/InjFfAWYHCDrenZlzQ
            91BzzeaKDzo8XReyDNbBRFFZWEDXe+bjlqiELX+Pj4yAW+0OnYbJbA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age135zaeaxu0elyxn9ax64dgw9hsxk2frpnqpj672w23qgcc8ewza0srpk0pc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-07T11:18:16Z"
    mac: ENC[AES256_GCM,data:851auAkwG24RdLP70R3uhSw6ay/U/+mXm4gQIFJFEDw+tF1XM8BFVFxg2Eiu9kImpnZ81wdResH3Mtoi3wIfWGNCcgB7zUjqBLxPsdqsSGe5ASXGdZ+WCrIAZJTUjkRxXOVgtZi3EUtQMKMnY3ElAJ0AFsAN37oohjnYf0X44ZI=,iv:JE7mbtCy5lL6sVFUk22AKtSyDCYDUSQMnVPYMq63KKQ=,tag:wHXzr6RGmoxIDLbkQcR5KA==,type:str]
    version: 3.13.3
