# Separate from the CNPG/Redis secrets because the app runs in default and needs full connection URIs.
apiVersion: v1
kind: Secret
metadata:
    name: aiometadata-secret
    namespace: default
stringData:
    DATABASE_URI: ENC[AES256_GCM,data:2mAv1A52WrERHlgSHp/nyxkruokXk5FGFf3J8HQxToqjCeLab7+VnYWQpeLu7sluwynwEmeks1lguJkU7XfB7t4/aDLKrmGOj+ppBfV+C37BB4ftmynkoru/Pglr3ijJ6+pJunz5lhNbhL5r66ztsCV8HNsRAT1hCUlGGaRig1iu,iv:r6qdTSYFM9Kuii/gN3Lo+rtmLuXBRMbaN3FbJwgGAco=,tag:Zd7tlYU2ioJrigjZhWsRzg==,type:str]
    REDIS_URL: ENC[AES256_GCM,data:7VAWYcX/+9Xhz0aHZPk+qlLxuO8U5Vxy/lgIN7NLAJflG2gcABRGlcnaSlxAq7rQ4YUgVY4X5wGdDZzmot0YFtPaGhdXQAOhFrZE2jXtUB28E3DbnQe1MjtXcQAN7mouww==,iv:jsh+cYpStSvfMaxRmZVzEgzXDJnDRPWzV6JxYPJj/Nk=,tag:jdd0CSMKPFW00Ho+9nJ+lQ==,type:str]
    ADMIN_KEY: ENC[AES256_GCM,data:PlI4XZmMD26/8RUy8ykyvydRc0LbfreOIO7UHhh66YEY9RQvFn8GKwLfXS5LQa/XKOn+gD9am2j2/l0CUSxfOA==,iv:09PYAh2mudoEAlR8QGylZlntR8EpcW2E3RQKRb7GSw8=,tag:F1CxvT2OvvtTTMlY3EG5BQ==,type:str]
    ADDON_PASSWORD: ENC[AES256_GCM,data:5tNVzYSY5ejK8fc7lbQk81h6yf2WttU3,iv:FGZCbLcWzlONNtaLfiZVQeqjn937KrumP/JfAT/KQVI=,tag:8MA9UlADkL1lAZKMGi9Zng==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0NW1qeHFXdlNHNTZUbnli
            UjF3S2pmamEyOUdDdGJMQzJieEZkL2lwcVZNClFMRmtMZGVmUFFuMEJ6K3VuQk9h
            WnlrMDRuZ0dyRmZHM2dMY3VqZmJhZWcKLS0tIE9YNjV6TXU4REdmNGV6RGhkQzd0
            R21Ta21QQktMNUxKZmlJODJ2K2lLcU0K7Uls8muZHQM378ZlSyORZ00g1YcrQUgx
            ZnnB9mcExCqnW+hb1N/CHzV+bwF5kiqTi3DKpY64wQmjumrZ2V9JxQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age135zaeaxu0elyxn9ax64dgw9hsxk2frpnqpj672w23qgcc8ewza0srpk0pc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-07T11:18:22Z"
    mac: ENC[AES256_GCM,data:4W8lUIytPQCaxHdT2yUvn1bu98RnwfL034CliYz/hn3+P7GbO0lbXI2HG9Y8b0EHpSn4OBzxa2ZaMLTLaH5wfjNB8ObXlYuozoU196lphomvFr26ACGmFPMN3it5SJuqDNUKoa/4Kx4EmP+kxJkeER1Om7Q99U8qBZFEOhRr8Uo=,iv:n3pK33UErHnsyK/uw4DKRKRfEz/R/1qYjHdD96f+rhs=,tag:HGKCRpi87dv1nUDTP1wPuA==,type:str]
    version: 3.13.3
