apiVersion: v1
kind: Secret
metadata:
    name: vibe-secret
    namespace: default
type: Opaque
stringData:
    VIBE_ADMIN_TOKEN: ENC[AES256_GCM,data:Iyi4x1hzDzZ52y+UjviVL1WI0Sw51lTyy0kVZY/N/lzgnN4MgKIe/jvAmVyiqON+I4t5LXYEbAOvTnR/XAuxSQ==,iv:Jyfapg98KryqE0mL/xzj4UARXJsbLyaDruTYhv58rV8=,tag:A73pgRpEHfmqg4Npc6DL6w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzbVVlVTMrRFJ3UnRsc21i
            VDVlS2phWGxKdW1mczNjME1JQUw4aTNwN2lBCk1ucXFuTStOMXhndnZHUzhlVkdi
            dEcrNlF6T0lZbUQxUW1pMVRWNE9PUjAKLS0tIDU4c0hEdDIyZlRvWmUzYXlKdFNN
            Z0hjSC9OYTdqb2tUWDJZMWRHVGRaU0kKGARA9PgD7z0ZjlFvQMOJ6LXKjSma61tl
            jIxMu5aLb+tX/oZCL68e+Knz58wzg3Kzi/dxcgT4edvCIini6fJ4xQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age135zaeaxu0elyxn9ax64dgw9hsxk2frpnqpj672w23qgcc8ewza0srpk0pc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T15:23:06Z"
    mac: ENC[AES256_GCM,data:3oYuC/laBmAes/ZVbXSjRkxwU9SIBMa0Cyznx8VZ7bn0/NxUiYO5+I6/5Rz82V8I1KgZSv+QTnM0N5/P/UACivi69cjkw4Jpizgf+zPE24EQ9uM9lNCiRk3k/bquvruwe7wnYi15ipDG534fQ9PYt+it+w13CJAGZ1frysD+7fE=,iv:M6lfnexUL8FyzfkCNM7Ixh42O3LeuK5x+vdrC848oTQ=,tag:Ea6z6UO1QTc4rgYAtmmITA==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: vibe-worker-env
    namespace: default
type: Opaque
stringData:
    GH_TOKEN: ENC[AES256_GCM,data:i0tMthztu/Xq6jI+3QB8WwkJXRiab94CKOKORp8dWiUaem3eBTCm4A==,iv:9Q+RZv1NsJ6Y2Xbcxvs0pnbJX6IHBywJLzyPAfcBjuU=,tag:SZz5A1o7QF4URJG9gPZviw==,type:str]
    AZURE_DEVOPS_EXT_PAT: ENC[AES256_GCM,data:GKBCBEbC4PGj+iEXJgCqfHCpHoqyE2f4APFGhpRnh5Iv7FoLSL/CxJwPSNyIWnv/qN4Y1sO6eOsQxBt49IHkdhVvC2PQ7zcPHWd+5fwPYpYMP2b4,iv:xGDjUcSZxIb2tYZnsng4uKVZz9boFkmeRgm+VXz+X1M=,tag:tglplmgyhQ65iPF1DkFBZg==,type:str]
    GIT_AUTHOR_NAME: ENC[AES256_GCM,data:yGFhFno=,iv:zPyLfV8oEMTW2I5M4pbdrD302V92PYZSaCiAi4OO1SE=,tag:lIp4iTUJb1Ovd2F/TU5A0A==,type:str]
    GIT_AUTHOR_EMAIL: ENC[AES256_GCM,data:SWFjoERUnyew9GLc,iv:HhqtrUCuTu1O1QBTMICFTwr2ue3w5MZ9FLqJ4E4MIKM=,tag:P6Ho47HRg+rjDcGZHFO08w==,type:str]
    GIT_COMMITTER_NAME: ENC[AES256_GCM,data:4AjE24E=,iv:mqSpStRKhbT3JOdtLf7yxrS4scD84BbUwBWW3HOettw=,tag:6R6cCZyDwBJZSkQXr0awoA==,type:str]
    GIT_COMMITTER_EMAIL: ENC[AES256_GCM,data:vNtrQNGtw+TSxHU+,iv:mK0IDQcEk+lTyd1YfU2ZDo4tdGpniP+DV6Kke107Y1I=,tag:6BKdLWJUMDw3aYwsPnoj8w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzbVVlVTMrRFJ3UnRsc21i
            VDVlS2phWGxKdW1mczNjME1JQUw4aTNwN2lBCk1ucXFuTStOMXhndnZHUzhlVkdi
            dEcrNlF6T0lZbUQxUW1pMVRWNE9PUjAKLS0tIDU4c0hEdDIyZlRvWmUzYXlKdFNN
            Z0hjSC9OYTdqb2tUWDJZMWRHVGRaU0kKGARA9PgD7z0ZjlFvQMOJ6LXKjSma61tl
            jIxMu5aLb+tX/oZCL68e+Knz58wzg3Kzi/dxcgT4edvCIini6fJ4xQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age135zaeaxu0elyxn9ax64dgw9hsxk2frpnqpj672w23qgcc8ewza0srpk0pc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T15:23:06Z"
    mac: ENC[AES256_GCM,data:3oYuC/laBmAes/ZVbXSjRkxwU9SIBMa0Cyznx8VZ7bn0/NxUiYO5+I6/5Rz82V8I1KgZSv+QTnM0N5/P/UACivi69cjkw4Jpizgf+zPE24EQ9uM9lNCiRk3k/bquvruwe7wnYi15ipDG534fQ9PYt+it+w13CJAGZ1frysD+7fE=,iv:M6lfnexUL8FyzfkCNM7Ixh42O3LeuK5x+vdrC848oTQ=,tag:Ea6z6UO1QTc4rgYAtmmITA==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: vibe-postgres-credentials
    namespace: database
    labels:
        cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:XwIaJg==,iv:+AuMQaUsrR6LKoJ+raGzJhhUS2teUkvq1Y+HkRw5Ehg=,tag:ipM6WPPP1E8DsxkERim79g==,type:str]
    password: ENC[AES256_GCM,data:D0bBuKxdOawf+7WJRsH47a4DvziJTd8Hx1wBDCpsyl8LYpTM1DAn+K1wVy15W+ZM,iv:biQpMEkghtludYbkH4dvQIRKgJ6DA0HeOJ0CYLzvkAU=,tag:RdIkTFMkbdGNpC1JwYhGMw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzbVVlVTMrRFJ3UnRsc21i
            VDVlS2phWGxKdW1mczNjME1JQUw4aTNwN2lBCk1ucXFuTStOMXhndnZHUzhlVkdi
            dEcrNlF6T0lZbUQxUW1pMVRWNE9PUjAKLS0tIDU4c0hEdDIyZlRvWmUzYXlKdFNN
            Z0hjSC9OYTdqb2tUWDJZMWRHVGRaU0kKGARA9PgD7z0ZjlFvQMOJ6LXKjSma61tl
            jIxMu5aLb+tX/oZCL68e+Knz58wzg3Kzi/dxcgT4edvCIini6fJ4xQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age135zaeaxu0elyxn9ax64dgw9hsxk2frpnqpj672w23qgcc8ewza0srpk0pc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T15:23:06Z"
    mac: ENC[AES256_GCM,data:3oYuC/laBmAes/ZVbXSjRkxwU9SIBMa0Cyznx8VZ7bn0/NxUiYO5+I6/5Rz82V8I1KgZSv+QTnM0N5/P/UACivi69cjkw4Jpizgf+zPE24EQ9uM9lNCiRk3k/bquvruwe7wnYi15ipDG534fQ9PYt+it+w13CJAGZ1frysD+7fE=,iv:M6lfnexUL8FyzfkCNM7Ixh42O3LeuK5x+vdrC848oTQ=,tag:Ea6z6UO1QTc4rgYAtmmITA==,type:str]
    version: 3.13.3
---
apiVersion: v1
kind: Secret
metadata:
    name: vibe-postgres-credentials
    namespace: default
type: kubernetes.io/basic-auth
stringData:
    username: ENC[AES256_GCM,data:HpVVhg==,iv:wx/6CRNj4huKUe8ml/IIhWiwPyJLRKnIGzS2BlISTKY=,tag:nDVMeLmZZk31OaELZTTaOg==,type:str]
    password: ENC[AES256_GCM,data:DWxtjC+7jexCgK8yY2VK0M7L641wP67yQ81XzP1MniTRzppAkJwicbcTcpAuoG/4,iv:66cYO60ir1VkRXgJ5xBNMYyuaW7GCtOIQfGZQZ7SMdU=,tag:J+KMiKsxTn+h2i/454w4Ng==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzbVVlVTMrRFJ3UnRsc21i
            VDVlS2phWGxKdW1mczNjME1JQUw4aTNwN2lBCk1ucXFuTStOMXhndnZHUzhlVkdi
            dEcrNlF6T0lZbUQxUW1pMVRWNE9PUjAKLS0tIDU4c0hEdDIyZlRvWmUzYXlKdFNN
            Z0hjSC9OYTdqb2tUWDJZMWRHVGRaU0kKGARA9PgD7z0ZjlFvQMOJ6LXKjSma61tl
            jIxMu5aLb+tX/oZCL68e+Knz58wzg3Kzi/dxcgT4edvCIini6fJ4xQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age135zaeaxu0elyxn9ax64dgw9hsxk2frpnqpj672w23qgcc8ewza0srpk0pc
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-09T15:23:06Z"
    mac: ENC[AES256_GCM,data:3oYuC/laBmAes/ZVbXSjRkxwU9SIBMa0Cyznx8VZ7bn0/NxUiYO5+I6/5Rz82V8I1KgZSv+QTnM0N5/P/UACivi69cjkw4Jpizgf+zPE24EQ9uM9lNCiRk3k/bquvruwe7wnYi15ipDG534fQ9PYt+it+w13CJAGZ1frysD+7fE=,iv:M6lfnexUL8FyzfkCNM7Ixh42O3LeuK5x+vdrC848oTQ=,tag:Ea6z6UO1QTc4rgYAtmmITA==,type:str]
    version: 3.13.3
